import { identifyProduct, REVIEWED_PRODUCTS, type ProductIdentity } from "./product-identity";
import type { KeywordBenchmarkRun } from "./keyword-benchmark-types";
import { keywordRecommendationMetrics, keywordPublicUrl } from "./keyword-search-mode";
export type VisibilityRun = Pick<KeywordBenchmarkRun,"id"|"caseId"|"suiteId"|"case"|"status"|"model"|"harnessVersion"|"createdAt"|"answer">;
const host = (url: string) => keywordPublicUrl(url,false)?.hostname.replace(/\.$/,"").replace(/^www\./,"") ?? null;
export function visibilityReport(runs: VisibilityRun[], registry:ProductIdentity[]=REVIEWED_PRODUCTS) {
  const ordered = [...runs].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)||b.id.localeCompare(a.id));
  const latest = new Map<string,VisibilityRun>();
  for(const run of ordered) if(run.status==="completed"&&run.answer&&!latest.has(run.caseId)) latest.set(run.caseId,run);
  const prompts = [...latest.values()].map(run=>({caseId:run.caseId,suiteId:run.suiteId,query:run.case.query,runId:run.id,observedAt:run.createdAt,model:run.model,harnessVersion:run.harnessVersion,language:run.case.language,locale:run.case.locale,...keywordRecommendationMetrics(run)}));
  const known = prompts.filter(p=>p.targetNamed!=="unknown"), appeared=known.filter(p=>p.targetNamed==="yes");
  const positions=appeared.map(p=>p.targetPositions[0]);
  const domains=new Map<string,{domain:string;answers:number;positions:number[]}>();
  for(const p of prompts){const seen=new Set<string>();for(const r of p.recommendations) if(r.domain&&!seen.has(r.domain)){seen.add(r.domain);const item=domains.get(r.domain)??{domain:r.domain,answers:0,positions:[]};item.answers++;item.positions.push(r.position);domains.set(r.domain,item);}}
  const totalMentions=[...domains.values()].reduce((sum,d)=>sum+d.answers,0);
  const competitors=[...domains.values()].sort((a,b)=>b.answers-a.answers||a.domain.localeCompare(b.domain)).map(d=>({domain:d.domain,answers:d.answers,shareOfVoice:totalMentions?100*d.answers/totalMentions:null,averagePosition:d.positions.reduce((a,b)=>a+b,0)/d.positions.length,isTarget:prompts.some(p=>p.targetDomain===d.domain)}));
  const products=new Map<string,{id:string;name:string;answers:number;positions:number[];observations:{name:string;url:string|null;matchingMethod:string}[]}>();
  let unknownProductMentions=0;
  for(const p of prompts){const seen=new Set<string>();for(const r of p.recommendations){const product=identifyProduct(r.name,r.url,registry);if(!product){unknownProductMentions++;continue;}const item=products.get(product.id)??{id:product.id,name:product.name,answers:0,positions:[],observations:[]};item.observations.push({name:r.name,url:r.url,matchingMethod:product.matchingMethod});if(!seen.has(product.id)){seen.add(product.id);item.answers++;item.positions.push(r.position);}products.set(product.id,item);}}
  const productDenominator=[...products.values()].reduce((n,p)=>n+p.answers,0);
  const productComparison={denominator:productDenominator,unknownMentions:unknownProductMentions,method:"Reviewed product aliases and canonical URLs; unresolved identities are excluded. Each product counts once per answer.",products:[...products.values()].map(p=>({...p,shareOfVoice:productDenominator?100*p.answers/productDenominator:null}))};
  const citations=new Map<string,{url:string;title:string;sourceType:"owned"|"external";answers:number;runIds:string[]}>();
  for(const run of latest.values()){const seen=new Set<string>();for(const c of run.answer!.citations){if(!host(c.url)||seen.has(c.url))continue;seen.add(c.url);const item=citations.get(c.url)??{url:c.url,title:c.title??c.url,sourceType:host(c.url)===host(run.case.targetUrl??"")?"owned":"external",answers:0,runIds:[]};item.answers++;item.runIds.push(run.id);citations.set(c.url,item);}}
  const recommendations=prompts.flatMap(p=>p.targetNamed==="no"?[{id:`coverage-${p.caseId}`,title:"Review evidence for this question",pageEvidence:{tool:"folio_page_evidence",state:"not_assessed"},action:`Review the cited competitor pages for “${p.query}”. Inspect saved page evidence first to see whether the topic already exists. Propose an edit only where the observed content supports it.`,basis:"Your website was not listed in this saved answer.",caseId:p.caseId,runId:p.runId,sourceUrls:p.recommendations.flatMap(r=>r.citationUrls).slice(0,5)}]:p.targetNamed==="yes"&&p.targetCited===false?[{id:`citation-${p.caseId}`,title:"Make the supporting documentation easier to find",action:`For “${p.query}”, link directly to a public page supporting your product’s relevant capabilities. Check that its claims are specific and verifiable.`,basis:"Your website was listed but no source on its domain was cited.",caseId:p.caseId,runId:p.runId,sourceUrls:[] as string[]}]:[]);
  return {current:{completedQuestions:prompts.length,identifiedQuestions:known.length,unknownQuestions:prompts.length-known.length,mentionedQuestions:appeared.length,visibilityScore:known.length?100*appeared.length/known.length:null,shareOfVoice:known.length&&totalMentions?(competitors.find(c=>c.isTarget)?.shareOfVoice??0):null,averagePosition:positions.length?positions.reduce((a,b)=>a+b,0)/positions.length:null},prompts,competitors,citationHostComparison:{denominator:totalMentions,unknownMentions:prompts.reduce((n,p)=>n+p.recommendations.filter(r=>!r.domain).length,0),method:"Each recommendation URL host counts once per answer",hosts:competitors},productComparison,citations:[...citations.values()].sort((a,b)=>b.answers-a.answers||a.url.localeCompare(b.url)),recommendations};
}
