-- Private cumulative usage snapshots, not a customer wallet or provider invoice.
CREATE TABLE provider_cost_rates (
  model TEXT PRIMARY KEY, version TEXT NOT NULL,
  input_usd_per_million REAL NOT NULL, cached_usd_per_million REAL NOT NULL,
  output_usd_per_million REAL NOT NULL
);
INSERT INTO provider_cost_rates VALUES
 ('gpt-6-astra','openai-standard-short-2026-09-18',10,1,50),
 ('gpt-5.6-sol','openai-standard-short-2026-09-18',4,0.4,20),
 ('gpt-5.6-terra','openai-standard-short-2026-09-18',2,0.2,12),
 ('gpt-5.6-luna','openai-standard-short-2026-09-18',0.2,0.02,1.2);
CREATE TABLE provider_cost_observations (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 user_id TEXT NOT NULL REFERENCES user(id) ON DELETE CASCADE,
 source TEXT NOT NULL CHECK(source IN ('keyword','evaluation','seo')),
 source_id TEXT NOT NULL, source_revision INTEGER NOT NULL,
 provider TEXT NOT NULL, model TEXT, status TEXT NOT NULL,
 source_created_at INTEGER NOT NULL, observed_at INTEGER NOT NULL,
 input_tokens INTEGER, cached_input_tokens INTEGER, output_tokens INTEGER,
 estimated_token_micros INTEGER, reported_known_micros INTEGER,
 reported_complete INTEGER NOT NULL DEFAULT 0,
 rate_version TEXT,
 UNIQUE(user_id,source,source_id,source_revision),
 CHECK(estimated_token_micros IS NULL OR estimated_token_micros >= 0),
 CHECK(reported_known_micros IS NULL OR reported_known_micros >= 0)
);
CREATE INDEX provider_cost_owner ON provider_cost_observations(user_id,source,source_id,id DESC);
-- Updates cannot rewrite the historical estimate or its rate version.
CREATE TRIGGER provider_cost_append_only BEFORE UPDATE ON provider_cost_observations
BEGIN SELECT RAISE(ABORT,'Cost observations are append-only'); END;
CREATE VIEW provider_cost_latest AS SELECT o.* FROM provider_cost_observations o
WHERE o.id = (SELECT MAX(n.id) FROM provider_cost_observations n
 WHERE n.user_id=o.user_id AND n.source=o.source AND n.source_id=o.source_id);
INSERT OR IGNORE INTO provider_cost_observations (user_id,source,source_id,source_revision,provider,model,status,source_created_at,observed_at,input_tokens,cached_input_tokens,output_tokens,estimated_token_micros,reported_known_micros,reported_complete,rate_version) SELECT u.user_id,u.source,u.source_id,u.source_revision,u.provider,u.model,u.status,u.source_created_at,u.observed_at,u.input_tokens,u.cached_input_tokens,u.output_tokens,iif(u.input_tokens IS NOT NULL AND u.output_tokens IS NOT NULL AND r.model IS NOT NULL AND (u.cached_input_tokens IS NULL OR u.cached_input_tokens<=u.input_tokens),CAST(ROUND((u.input_tokens-COALESCE(u.cached_input_tokens,0))*r.input_usd_per_million+COALESCE(u.cached_input_tokens,0)*r.cached_usd_per_million+u.output_tokens*r.output_usd_per_million) AS INTEGER),NULL),u.reported_known_micros,u.reported_complete,r.version FROM (SELECT s.user_id user_id,'keyword' source,s.id source_id,s.revision source_revision,'openai' provider,s.model model,s.status status,s.created_at source_created_at,CAST(unixepoch('now')*1000 AS INTEGER) observed_at,iif(json_type(s.usage_json,'$.inputTokens')='integer' AND json_extract(s.usage_json,'$.inputTokens') BETWEEN 0 AND 1000000000000,json_extract(s.usage_json,'$.inputTokens'),NULL) input_tokens,iif(json_type(s.usage_json,'$.cachedInputTokens')='integer' AND json_extract(s.usage_json,'$.cachedInputTokens') BETWEEN 0 AND 1000000000000,json_extract(s.usage_json,'$.cachedInputTokens'),NULL) cached_input_tokens,iif(json_type(s.usage_json,'$.outputTokens')='integer' AND json_extract(s.usage_json,'$.outputTokens') BETWEEN 0 AND 1000000000000,json_extract(s.usage_json,'$.outputTokens'),NULL) output_tokens,NULL reported_known_micros,0 reported_complete FROM keyword_benchmark_runs s WHERE 1=1) u LEFT JOIN provider_cost_rates r ON r.model=u.model;
CREATE TRIGGER cost_keyword_insert AFTER INSERT ON keyword_benchmark_runs

BEGIN
INSERT OR IGNORE INTO provider_cost_observations (user_id,source,source_id,source_revision,provider,model,status,source_created_at,observed_at,input_tokens,cached_input_tokens,output_tokens,estimated_token_micros,reported_known_micros,reported_complete,rate_version) SELECT u.user_id,u.source,u.source_id,u.source_revision,u.provider,u.model,u.status,u.source_created_at,u.observed_at,u.input_tokens,u.cached_input_tokens,u.output_tokens,iif(u.input_tokens IS NOT NULL AND u.output_tokens IS NOT NULL AND r.model IS NOT NULL AND (u.cached_input_tokens IS NULL OR u.cached_input_tokens<=u.input_tokens),CAST(ROUND((u.input_tokens-COALESCE(u.cached_input_tokens,0))*r.input_usd_per_million+COALESCE(u.cached_input_tokens,0)*r.cached_usd_per_million+u.output_tokens*r.output_usd_per_million) AS INTEGER),NULL),u.reported_known_micros,u.reported_complete,r.version FROM (SELECT NEW.user_id user_id,'keyword' source,NEW.id source_id,NEW.revision source_revision,'openai' provider,NEW.model model,NEW.status status,NEW.created_at source_created_at,CAST(unixepoch('now')*1000 AS INTEGER) observed_at,iif(json_type(NEW.usage_json,'$.inputTokens')='integer' AND json_extract(NEW.usage_json,'$.inputTokens') BETWEEN 0 AND 1000000000000,json_extract(NEW.usage_json,'$.inputTokens'),NULL) input_tokens,iif(json_type(NEW.usage_json,'$.cachedInputTokens')='integer' AND json_extract(NEW.usage_json,'$.cachedInputTokens') BETWEEN 0 AND 1000000000000,json_extract(NEW.usage_json,'$.cachedInputTokens'),NULL) cached_input_tokens,iif(json_type(NEW.usage_json,'$.outputTokens')='integer' AND json_extract(NEW.usage_json,'$.outputTokens') BETWEEN 0 AND 1000000000000,json_extract(NEW.usage_json,'$.outputTokens'),NULL) output_tokens,NULL reported_known_micros,0 reported_complete WHERE 1=1) u LEFT JOIN provider_cost_rates r ON r.model=u.model;
END;
CREATE TRIGGER cost_keyword_update AFTER UPDATE ON keyword_benchmark_runs
WHEN NEW.usage_json IS NOT OLD.usage_json OR NEW.status IS NOT OLD.status
BEGIN
INSERT OR IGNORE INTO provider_cost_observations (user_id,source,source_id,source_revision,provider,model,status,source_created_at,observed_at,input_tokens,cached_input_tokens,output_tokens,estimated_token_micros,reported_known_micros,reported_complete,rate_version) SELECT u.user_id,u.source,u.source_id,u.source_revision,u.provider,u.model,u.status,u.source_created_at,u.observed_at,u.input_tokens,u.cached_input_tokens,u.output_tokens,iif(u.input_tokens IS NOT NULL AND u.output_tokens IS NOT NULL AND r.model IS NOT NULL AND (u.cached_input_tokens IS NULL OR u.cached_input_tokens<=u.input_tokens),CAST(ROUND((u.input_tokens-COALESCE(u.cached_input_tokens,0))*r.input_usd_per_million+COALESCE(u.cached_input_tokens,0)*r.cached_usd_per_million+u.output_tokens*r.output_usd_per_million) AS INTEGER),NULL),u.reported_known_micros,u.reported_complete,r.version FROM (SELECT NEW.user_id user_id,'keyword' source,NEW.id source_id,NEW.revision source_revision,'openai' provider,NEW.model model,NEW.status status,NEW.created_at source_created_at,CAST(unixepoch('now')*1000 AS INTEGER) observed_at,iif(json_type(NEW.usage_json,'$.inputTokens')='integer' AND json_extract(NEW.usage_json,'$.inputTokens') BETWEEN 0 AND 1000000000000,json_extract(NEW.usage_json,'$.inputTokens'),NULL) input_tokens,iif(json_type(NEW.usage_json,'$.cachedInputTokens')='integer' AND json_extract(NEW.usage_json,'$.cachedInputTokens') BETWEEN 0 AND 1000000000000,json_extract(NEW.usage_json,'$.cachedInputTokens'),NULL) cached_input_tokens,iif(json_type(NEW.usage_json,'$.outputTokens')='integer' AND json_extract(NEW.usage_json,'$.outputTokens') BETWEEN 0 AND 1000000000000,json_extract(NEW.usage_json,'$.outputTokens'),NULL) output_tokens,NULL reported_known_micros,0 reported_complete WHERE 1=1) u LEFT JOIN provider_cost_rates r ON r.model=u.model;
END;
INSERT OR IGNORE INTO provider_cost_observations (user_id,source,source_id,source_revision,provider,model,status,source_created_at,observed_at,input_tokens,cached_input_tokens,output_tokens,estimated_token_micros,reported_known_micros,reported_complete,rate_version) SELECT u.user_id,u.source,u.source_id,u.source_revision,u.provider,u.model,u.status,u.source_created_at,u.observed_at,u.input_tokens,u.cached_input_tokens,u.output_tokens,iif(u.input_tokens IS NOT NULL AND u.output_tokens IS NOT NULL AND r.model IS NOT NULL AND (u.cached_input_tokens IS NULL OR u.cached_input_tokens<=u.input_tokens),CAST(ROUND((u.input_tokens-COALESCE(u.cached_input_tokens,0))*r.input_usd_per_million+COALESCE(u.cached_input_tokens,0)*r.cached_usd_per_million+u.output_tokens*r.output_usd_per_million) AS INTEGER),NULL),u.reported_known_micros,u.reported_complete,r.version FROM (SELECT s.user_id user_id,'evaluation' source,s.id source_id,s.revision source_revision,'openai' provider,json_extract(s.result_json,'$.model') model,s.status status,s.created_at source_created_at,CAST(unixepoch('now')*1000 AS INTEGER) observed_at,iif(json_type(s.result_json,'$.usage.input_tokens')='integer' AND json_extract(s.result_json,'$.usage.input_tokens') BETWEEN 0 AND 1000000000000,json_extract(s.result_json,'$.usage.input_tokens'),NULL) input_tokens,iif(json_type(s.result_json,'$.usage.input_tokens_details.cached_tokens')='integer' AND json_extract(s.result_json,'$.usage.input_tokens_details.cached_tokens') BETWEEN 0 AND 1000000000000,json_extract(s.result_json,'$.usage.input_tokens_details.cached_tokens'),NULL) cached_input_tokens,iif(json_type(s.result_json,'$.usage.output_tokens')='integer' AND json_extract(s.result_json,'$.usage.output_tokens') BETWEEN 0 AND 1000000000000,json_extract(s.result_json,'$.usage.output_tokens'),NULL) output_tokens,NULL reported_known_micros,0 reported_complete FROM evaluation_runs s WHERE s.mode='live' AND s.deleted_at IS NULL) u LEFT JOIN provider_cost_rates r ON r.model=u.model;
CREATE TRIGGER cost_evaluation_insert AFTER INSERT ON evaluation_runs

BEGIN
INSERT OR IGNORE INTO provider_cost_observations (user_id,source,source_id,source_revision,provider,model,status,source_created_at,observed_at,input_tokens,cached_input_tokens,output_tokens,estimated_token_micros,reported_known_micros,reported_complete,rate_version) SELECT u.user_id,u.source,u.source_id,u.source_revision,u.provider,u.model,u.status,u.source_created_at,u.observed_at,u.input_tokens,u.cached_input_tokens,u.output_tokens,iif(u.input_tokens IS NOT NULL AND u.output_tokens IS NOT NULL AND r.model IS NOT NULL AND (u.cached_input_tokens IS NULL OR u.cached_input_tokens<=u.input_tokens),CAST(ROUND((u.input_tokens-COALESCE(u.cached_input_tokens,0))*r.input_usd_per_million+COALESCE(u.cached_input_tokens,0)*r.cached_usd_per_million+u.output_tokens*r.output_usd_per_million) AS INTEGER),NULL),u.reported_known_micros,u.reported_complete,r.version FROM (SELECT NEW.user_id user_id,'evaluation' source,NEW.id source_id,NEW.revision source_revision,'openai' provider,json_extract(NEW.result_json,'$.model') model,NEW.status status,NEW.created_at source_created_at,CAST(unixepoch('now')*1000 AS INTEGER) observed_at,iif(json_type(NEW.result_json,'$.usage.input_tokens')='integer' AND json_extract(NEW.result_json,'$.usage.input_tokens') BETWEEN 0 AND 1000000000000,json_extract(NEW.result_json,'$.usage.input_tokens'),NULL) input_tokens,iif(json_type(NEW.result_json,'$.usage.input_tokens_details.cached_tokens')='integer' AND json_extract(NEW.result_json,'$.usage.input_tokens_details.cached_tokens') BETWEEN 0 AND 1000000000000,json_extract(NEW.result_json,'$.usage.input_tokens_details.cached_tokens'),NULL) cached_input_tokens,iif(json_type(NEW.result_json,'$.usage.output_tokens')='integer' AND json_extract(NEW.result_json,'$.usage.output_tokens') BETWEEN 0 AND 1000000000000,json_extract(NEW.result_json,'$.usage.output_tokens'),NULL) output_tokens,NULL reported_known_micros,0 reported_complete WHERE NEW.mode='live' AND NEW.deleted_at IS NULL) u LEFT JOIN provider_cost_rates r ON r.model=u.model;
END;
CREATE TRIGGER cost_evaluation_update AFTER UPDATE ON evaluation_runs
WHEN (json_extract(NEW.result_json,'$.usage') IS NOT json_extract(OLD.result_json,'$.usage') OR NEW.status IS NOT OLD.status) AND NEW.deleted_at IS NULL
BEGIN
INSERT OR IGNORE INTO provider_cost_observations (user_id,source,source_id,source_revision,provider,model,status,source_created_at,observed_at,input_tokens,cached_input_tokens,output_tokens,estimated_token_micros,reported_known_micros,reported_complete,rate_version) SELECT u.user_id,u.source,u.source_id,u.source_revision,u.provider,u.model,u.status,u.source_created_at,u.observed_at,u.input_tokens,u.cached_input_tokens,u.output_tokens,iif(u.input_tokens IS NOT NULL AND u.output_tokens IS NOT NULL AND r.model IS NOT NULL AND (u.cached_input_tokens IS NULL OR u.cached_input_tokens<=u.input_tokens),CAST(ROUND((u.input_tokens-COALESCE(u.cached_input_tokens,0))*r.input_usd_per_million+COALESCE(u.cached_input_tokens,0)*r.cached_usd_per_million+u.output_tokens*r.output_usd_per_million) AS INTEGER),NULL),u.reported_known_micros,u.reported_complete,r.version FROM (SELECT NEW.user_id user_id,'evaluation' source,NEW.id source_id,NEW.revision source_revision,'openai' provider,json_extract(NEW.result_json,'$.model') model,NEW.status status,NEW.created_at source_created_at,CAST(unixepoch('now')*1000 AS INTEGER) observed_at,iif(json_type(NEW.result_json,'$.usage.input_tokens')='integer' AND json_extract(NEW.result_json,'$.usage.input_tokens') BETWEEN 0 AND 1000000000000,json_extract(NEW.result_json,'$.usage.input_tokens'),NULL) input_tokens,iif(json_type(NEW.result_json,'$.usage.input_tokens_details.cached_tokens')='integer' AND json_extract(NEW.result_json,'$.usage.input_tokens_details.cached_tokens') BETWEEN 0 AND 1000000000000,json_extract(NEW.result_json,'$.usage.input_tokens_details.cached_tokens'),NULL) cached_input_tokens,iif(json_type(NEW.result_json,'$.usage.output_tokens')='integer' AND json_extract(NEW.result_json,'$.usage.output_tokens') BETWEEN 0 AND 1000000000000,json_extract(NEW.result_json,'$.usage.output_tokens'),NULL) output_tokens,NULL reported_known_micros,0 reported_complete WHERE NEW.mode='live' AND NEW.deleted_at IS NULL) u LEFT JOIN provider_cost_rates r ON r.model=u.model;
END;
INSERT OR IGNORE INTO provider_cost_observations (user_id,source,source_id,source_revision,provider,model,status,source_created_at,observed_at,input_tokens,cached_input_tokens,output_tokens,estimated_token_micros,reported_known_micros,reported_complete,rate_version) SELECT u.user_id,u.source,u.source_id,u.source_revision,u.provider,u.model,u.status,u.source_created_at,u.observed_at,u.input_tokens,u.cached_input_tokens,u.output_tokens,iif(u.input_tokens IS NOT NULL AND u.output_tokens IS NOT NULL AND r.model IS NOT NULL AND (u.cached_input_tokens IS NULL OR u.cached_input_tokens<=u.input_tokens),CAST(ROUND((u.input_tokens-COALESCE(u.cached_input_tokens,0))*r.input_usd_per_million+COALESCE(u.cached_input_tokens,0)*r.cached_usd_per_million+u.output_tokens*r.output_usd_per_million) AS INTEGER),NULL),u.reported_known_micros,u.reported_complete,r.version FROM (SELECT s.user_id user_id,'seo' source,s.id source_id,COALESCE(s.retrieved_at,0) source_revision,'dataforseo' provider,NULL model,COALESCE(json_extract(s.result_json,'$.status'),'unconfirmed') status,s.created_at source_created_at,CAST(unixepoch('now')*1000 AS INTEGER) observed_at,NULL input_tokens,NULL cached_input_tokens,NULL output_tokens,iif(json_type(s.result_json,'$.totalCostUsd') IN ('integer','real') AND json_extract(s.result_json,'$.totalCostUsd') BETWEEN 0 AND 1000000,CAST(ROUND(json_extract(s.result_json,'$.totalCostUsd')*1000000) AS INTEGER),iif(json_type(s.result_json,'$.knownCostUsd') IN ('integer','real') AND json_extract(s.result_json,'$.knownCostUsd') BETWEEN 0 AND 1000000 AND (json_type(s.result_json,'$.organic.costUsd') IN ('integer','real') OR json_type(s.result_json,'$.backlinks.costUsd') IN ('integer','real')),CAST(ROUND(json_extract(s.result_json,'$.knownCostUsd')*1000000) AS INTEGER),NULL)) reported_known_micros,iif(json_extract(s.result_json,'$.costIsComplete')=1 AND json_type(s.result_json,'$.totalCostUsd') IN ('integer','real') AND json_extract(s.result_json,'$.totalCostUsd') BETWEEN 0 AND 1000000,1,0) reported_complete FROM seo_reports s WHERE 1=1) u LEFT JOIN provider_cost_rates r ON r.model=u.model;
CREATE TRIGGER cost_seo_insert AFTER INSERT ON seo_reports

BEGIN
INSERT OR IGNORE INTO provider_cost_observations (user_id,source,source_id,source_revision,provider,model,status,source_created_at,observed_at,input_tokens,cached_input_tokens,output_tokens,estimated_token_micros,reported_known_micros,reported_complete,rate_version) SELECT u.user_id,u.source,u.source_id,u.source_revision,u.provider,u.model,u.status,u.source_created_at,u.observed_at,u.input_tokens,u.cached_input_tokens,u.output_tokens,iif(u.input_tokens IS NOT NULL AND u.output_tokens IS NOT NULL AND r.model IS NOT NULL AND (u.cached_input_tokens IS NULL OR u.cached_input_tokens<=u.input_tokens),CAST(ROUND((u.input_tokens-COALESCE(u.cached_input_tokens,0))*r.input_usd_per_million+COALESCE(u.cached_input_tokens,0)*r.cached_usd_per_million+u.output_tokens*r.output_usd_per_million) AS INTEGER),NULL),u.reported_known_micros,u.reported_complete,r.version FROM (SELECT NEW.user_id user_id,'seo' source,NEW.id source_id,COALESCE(NEW.retrieved_at,0) source_revision,'dataforseo' provider,NULL model,COALESCE(json_extract(NEW.result_json,'$.status'),'unconfirmed') status,NEW.created_at source_created_at,CAST(unixepoch('now')*1000 AS INTEGER) observed_at,NULL input_tokens,NULL cached_input_tokens,NULL output_tokens,iif(json_type(NEW.result_json,'$.totalCostUsd') IN ('integer','real') AND json_extract(NEW.result_json,'$.totalCostUsd') BETWEEN 0 AND 1000000,CAST(ROUND(json_extract(NEW.result_json,'$.totalCostUsd')*1000000) AS INTEGER),iif(json_type(NEW.result_json,'$.knownCostUsd') IN ('integer','real') AND json_extract(NEW.result_json,'$.knownCostUsd') BETWEEN 0 AND 1000000 AND (json_type(NEW.result_json,'$.organic.costUsd') IN ('integer','real') OR json_type(NEW.result_json,'$.backlinks.costUsd') IN ('integer','real')),CAST(ROUND(json_extract(NEW.result_json,'$.knownCostUsd')*1000000) AS INTEGER),NULL)) reported_known_micros,iif(json_extract(NEW.result_json,'$.costIsComplete')=1 AND json_type(NEW.result_json,'$.totalCostUsd') IN ('integer','real') AND json_extract(NEW.result_json,'$.totalCostUsd') BETWEEN 0 AND 1000000,1,0) reported_complete WHERE 1=1) u LEFT JOIN provider_cost_rates r ON r.model=u.model;
END;
CREATE TRIGGER cost_seo_update AFTER UPDATE ON seo_reports
WHEN NEW.result_json IS NOT OLD.result_json
BEGIN
INSERT OR IGNORE INTO provider_cost_observations (user_id,source,source_id,source_revision,provider,model,status,source_created_at,observed_at,input_tokens,cached_input_tokens,output_tokens,estimated_token_micros,reported_known_micros,reported_complete,rate_version) SELECT u.user_id,u.source,u.source_id,u.source_revision,u.provider,u.model,u.status,u.source_created_at,u.observed_at,u.input_tokens,u.cached_input_tokens,u.output_tokens,iif(u.input_tokens IS NOT NULL AND u.output_tokens IS NOT NULL AND r.model IS NOT NULL AND (u.cached_input_tokens IS NULL OR u.cached_input_tokens<=u.input_tokens),CAST(ROUND((u.input_tokens-COALESCE(u.cached_input_tokens,0))*r.input_usd_per_million+COALESCE(u.cached_input_tokens,0)*r.cached_usd_per_million+u.output_tokens*r.output_usd_per_million) AS INTEGER),NULL),u.reported_known_micros,u.reported_complete,r.version FROM (SELECT NEW.user_id user_id,'seo' source,NEW.id source_id,COALESCE(NEW.retrieved_at,0) source_revision,'dataforseo' provider,NULL model,COALESCE(json_extract(NEW.result_json,'$.status'),'unconfirmed') status,NEW.created_at source_created_at,CAST(unixepoch('now')*1000 AS INTEGER) observed_at,NULL input_tokens,NULL cached_input_tokens,NULL output_tokens,iif(json_type(NEW.result_json,'$.totalCostUsd') IN ('integer','real') AND json_extract(NEW.result_json,'$.totalCostUsd') BETWEEN 0 AND 1000000,CAST(ROUND(json_extract(NEW.result_json,'$.totalCostUsd')*1000000) AS INTEGER),iif(json_type(NEW.result_json,'$.knownCostUsd') IN ('integer','real') AND json_extract(NEW.result_json,'$.knownCostUsd') BETWEEN 0 AND 1000000 AND (json_type(NEW.result_json,'$.organic.costUsd') IN ('integer','real') OR json_type(NEW.result_json,'$.backlinks.costUsd') IN ('integer','real')),CAST(ROUND(json_extract(NEW.result_json,'$.knownCostUsd')*1000000) AS INTEGER),NULL)) reported_known_micros,iif(json_extract(NEW.result_json,'$.costIsComplete')=1 AND json_type(NEW.result_json,'$.totalCostUsd') IN ('integer','real') AND json_extract(NEW.result_json,'$.totalCostUsd') BETWEEN 0 AND 1000000,1,0) reported_complete WHERE 1=1) u LEFT JOIN provider_cost_rates r ON r.model=u.model;
END;
