-- Derived from the final state of D1 migrations 0001-0021. Apply ONLY to a new empty PostgreSQL database.
-- Millisecond epoch timestamps and integer 0/1 flags intentionally remain BIGINT.
-- Private JSON payloads remain TEXT, preserving byte content and existing application contracts.
CREATE FUNCTION d1_json_valid(value text) RETURNS boolean LANGUAGE plpgsql IMMUTABLE AS $$
BEGIN PERFORM value::jsonb; RETURN true;
EXCEPTION WHEN others THEN RETURN false;
END $$;

-- A single locked row serializes Folio's existing count-then-write gates.
-- Hyperdrive does not support PostgreSQL advisory locks.
CREATE TABLE folio_write_gate (id INTEGER PRIMARY KEY CHECK (id = 1));
INSERT INTO folio_write_gate (id) VALUES (1);

-- Legacy production publication table predates the numbered application migrations.
-- It is read by workers/public-index.ts and must survive the D1 cutover.
CREATE TABLE published_question_snapshots (
  id TEXT PRIMARY KEY,
  summary_json TEXT NOT NULL CHECK (d1_json_valid(summary_json)),
  imported_at TEXT NOT NULL,
  source TEXT NOT NULL
);

CREATE TABLE background_job_leases (
  name TEXT PRIMARY KEY NOT NULL,
  token TEXT NOT NULL,
  expires_at BIGINT NOT NULL
);

CREATE TABLE provider_cost_rates (
  model TEXT PRIMARY KEY, version TEXT NOT NULL,
  input_usd_per_million DOUBLE PRECISION NOT NULL, cached_usd_per_million DOUBLE PRECISION NOT NULL,
  output_usd_per_million DOUBLE PRECISION NOT NULL
);

CREATE TABLE rate_limit (
  id TEXT PRIMARY KEY NOT NULL,
  key TEXT NOT NULL UNIQUE,
  count BIGINT NOT NULL,
  last_request BIGINT NOT NULL
);

CREATE TABLE "user" (
  id TEXT PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  email_verified BOOLEAN NOT NULL DEFAULT FALSE,
  image TEXT,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);

CREATE TABLE verification (
  id TEXT PRIMARY KEY NOT NULL,
  identifier TEXT NOT NULL,
  value TEXT NOT NULL,
  expires_at BIGINT NOT NULL,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);

CREATE TABLE account (
  id TEXT PRIMARY KEY NOT NULL,
  account_id TEXT NOT NULL,
  provider_id TEXT NOT NULL,
  user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  access_token TEXT,
  refresh_token TEXT,
  id_token TEXT,
  access_token_expires_at BIGINT,
  refresh_token_expires_at BIGINT,
  scope TEXT,
  password TEXT,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  UNIQUE(provider_id, account_id)
);

CREATE TABLE agent_api_keys (
  id TEXT PRIMARY KEY NOT NULL,
  user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  name TEXT NOT NULL CHECK(length(name) BETWEEN 1 AND 100),
  prefix TEXT NOT NULL,
  token_hash TEXT NOT NULL UNIQUE CHECK(length(token_hash)=64),
  scopes_json TEXT NOT NULL,
  created_at BIGINT NOT NULL,
  expires_at BIGINT NOT NULL,
  revoked_at BIGINT,
  last_used_at BIGINT,
  rate_window BIGINT NOT NULL DEFAULT 0,
  rate_count BIGINT NOT NULL DEFAULT 0,
  UNIQUE(id,user_id)
);

CREATE TABLE evaluation_runs (
  id TEXT PRIMARY KEY NOT NULL,
  user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  target_url TEXT NOT NULL,
  suite_version TEXT NOT NULL,
  mode TEXT NOT NULL CHECK(mode IN ('demo', 'live')),
  status TEXT NOT NULL CHECK(status IN ('queued', 'running', 'requires_action', 'completed', 'failed', 'cancelled')),
  session_id TEXT,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  revision BIGINT NOT NULL DEFAULT 0,
  result_json TEXT NOT NULL
, deleted_at BIGINT, background_checked_at BIGINT NOT NULL DEFAULT 0);

CREATE TABLE keyword_benchmark_suites (
  id TEXT PRIMARY KEY NOT NULL,
  user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  created_at BIGINT NOT NULL,
  UNIQUE(id, user_id)
);

CREATE TABLE plan_interest (
  user_id TEXT PRIMARY KEY NOT NULL REFERENCES "user"(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  plan_slug TEXT NOT NULL CHECK(plan_slug IN ('free','builder','team')),
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);

CREATE TABLE provider_cost_observations (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
 source TEXT NOT NULL CHECK(source IN ('keyword','evaluation','seo')),
 source_id TEXT NOT NULL, source_revision BIGINT NOT NULL,
 provider TEXT NOT NULL, model TEXT, status TEXT NOT NULL,
 source_created_at BIGINT NOT NULL, observed_at BIGINT NOT NULL,
 input_tokens BIGINT, cached_input_tokens BIGINT, output_tokens BIGINT,
 estimated_token_micros BIGINT, reported_known_micros BIGINT,
 reported_complete BIGINT NOT NULL DEFAULT 0,
 rate_version TEXT,
 UNIQUE(user_id,source,source_id,source_revision),
 CHECK(estimated_token_micros IS NULL OR estimated_token_micros >= 0),
 CHECK(reported_known_micros IS NULL OR reported_known_micros >= 0)
);

CREATE TABLE search_console_reports (
  id TEXT PRIMARY KEY NOT NULL,
  user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  property TEXT NOT NULL,
  created_at BIGINT NOT NULL,
  report_json TEXT NOT NULL CHECK (octet_length(report_json) <= 1000000),
  summary_json TEXT NOT NULL CHECK (octet_length(summary_json) <= 30000)
);

CREATE TABLE seo_agent_requests (
  id TEXT PRIMARY KEY NOT NULL,
  user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  idempotency_hash TEXT NOT NULL,
  request_hash TEXT NOT NULL,
  report_id TEXT NOT NULL,
  created_at BIGINT NOT NULL,
  UNIQUE(user_id,idempotency_hash)
);

CREATE TABLE seo_reports (
  id TEXT PRIMARY KEY NOT NULL,
  user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  domain TEXT NOT NULL,
  created_at BIGINT NOT NULL,
  retrieved_at BIGINT,
  result_json TEXT
);

CREATE TABLE session (
  id TEXT PRIMARY KEY NOT NULL,
  expires_at BIGINT NOT NULL,
  token TEXT NOT NULL UNIQUE,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  ip_address TEXT,
  user_agent TEXT,
  user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE sites (
  id TEXT PRIMARY KEY NOT NULL,
  user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  url TEXT NOT NULL,
  name TEXT NOT NULL,
  created_at BIGINT NOT NULL,
  is_public BIGINT NOT NULL DEFAULT 0 CHECK(is_public IN (0, 1)),
  UNIQUE(user_id, url)
);

CREATE TABLE typesafe_reviews (
 d1_rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
 id TEXT PRIMARY KEY,
 user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
 run_id TEXT NOT NULL,
 source_revision BIGINT NOT NULL,
 created_at BIGINT NOT NULL,
 updated_at BIGINT NOT NULL,
 status TEXT NOT NULL CHECK(status IN ('pending','completed','needs_attention')),
 model TEXT NOT NULL,
 input_tokens BIGINT,
 output_tokens BIGINT,
 latency_ms BIGINT,
 result_json TEXT,
 UNIQUE(user_id,run_id)
);

CREATE TABLE typesafe_tool_grants (
 id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
 run_id TEXT NOT NULL UNIQUE,token_hash TEXT NOT NULL UNIQUE,expires_at BIGINT NOT NULL
);

CREATE TABLE agent_api_requests (
  id TEXT PRIMARY KEY NOT NULL,
  user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  key_id TEXT NOT NULL,
  idempotency_hash TEXT NOT NULL CHECK(length(idempotency_hash)=64),
  request_hash TEXT NOT NULL CHECK(length(request_hash)=64),
  resource_kind TEXT NOT NULL CHECK(resource_kind IN ('website','keyword')),
  resource_id TEXT NOT NULL,
  run_id TEXT NOT NULL,
  disposition TEXT NOT NULL CHECK(disposition IN ('fresh_saved','existing_active','started','busy','denied')),
  created_at BIGINT NOT NULL,
  UNIQUE(user_id,idempotency_hash),
  FOREIGN KEY(key_id,user_id) REFERENCES agent_api_keys(id,user_id) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE agent_tool_calls (
  run_id TEXT PRIMARY KEY NOT NULL REFERENCES evaluation_runs(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  session_id TEXT NOT NULL,
  turn_id TEXT NOT NULL,
  call_id TEXT NOT NULL,
  tool_name TEXT NOT NULL CHECK(tool_name = 'read_saved_seo_report'),
  state TEXT NOT NULL CHECK(state IN ('reserved', 'submitted', 'uncertain')),
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  UNIQUE(session_id, turn_id, call_id)
);

CREATE TABLE keyword_benchmark_cases (
  id TEXT PRIMARY KEY NOT NULL,
  user_id TEXT NOT NULL,
  suite_id TEXT NOT NULL,
  revision BIGINT NOT NULL DEFAULT 0 CHECK(revision >= 0),
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  case_json TEXT NOT NULL CHECK(octet_length(case_json) <= 50000),
  UNIQUE(id, user_id),
  FOREIGN KEY(suite_id, user_id) REFERENCES keyword_benchmark_suites(id, user_id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE scans (
  id TEXT PRIMARY KEY NOT NULL,
  site_id TEXT NOT NULL REFERENCES sites(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  url TEXT NOT NULL,
  created_at BIGINT NOT NULL,
  seo_score DOUBLE PRECISION NOT NULL,
  result_json TEXT NOT NULL,
  evaluation_version TEXT NOT NULL DEFAULT 'readiness-v1'
);

CREATE TABLE typesafe_tool_calls (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,grant_id TEXT NOT NULL REFERENCES typesafe_tool_grants(id) DEFERRABLE INITIALLY DEFERRED,
 user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,request_key TEXT NOT NULL,input_hash TEXT NOT NULL,
 status TEXT NOT NULL,created_at BIGINT NOT NULL,updated_at BIGINT NOT NULL,
 model TEXT NOT NULL,input_tokens BIGINT,output_tokens BIGINT,latency_ms BIGINT,result_json TEXT,
 UNIQUE(grant_id,request_key)
);

CREATE TABLE website_crawl_grants (
 id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
 run_id TEXT NOT NULL UNIQUE REFERENCES evaluation_runs(id) DEFERRABLE INITIALLY DEFERRED, token_hash TEXT NOT NULL UNIQUE,
 target_url TEXT NOT NULL, expires_at BIGINT NOT NULL
);

CREATE TABLE keyword_benchmark_runs (
  id TEXT PRIMARY KEY NOT NULL,
  user_id TEXT NOT NULL,
  suite_id TEXT NOT NULL,
  case_id TEXT NOT NULL,
  kind TEXT NOT NULL CHECK(kind IN ('baseline', 'fresh')),
  baseline_run_id TEXT,
  model TEXT NOT NULL,
  harness_version TEXT NOT NULL,
  environment_type TEXT NOT NULL,
  environment_fingerprint TEXT NOT NULL,
  case_json TEXT NOT NULL CHECK(octet_length(case_json) <= 50000),
  status TEXT NOT NULL CHECK(status IN ('queued','running','requires_action','completed','failed','cancelled')),
  session_id TEXT,
  create_attempt_at BIGINT,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  revision BIGINT NOT NULL DEFAULT 0 CHECK(revision >= 0),
  answer_json TEXT CHECK(answer_json IS NULL OR octet_length(answer_json) <= 1000000),
  usage_json TEXT NOT NULL,
  provider_metadata_json TEXT NOT NULL,
  error TEXT,
  answer_characters BIGINT NOT NULL DEFAULT 0,
  mention_count BIGINT NOT NULL DEFAULT 0,
  citation_count BIGINT NOT NULL DEFAULT 0, allowed_domains_json TEXT NOT NULL DEFAULT '[]', deadline_at BIGINT, cancel_attempt_at BIGINT, cancel_acknowledged_at BIGINT, hold_release_at BIGINT, hold_release_reason TEXT, archived_at BIGINT,
  UNIQUE(id, user_id),
  FOREIGN KEY(suite_id, user_id) REFERENCES keyword_benchmark_suites(id, user_id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(case_id, user_id) REFERENCES keyword_benchmark_cases(id, user_id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(baseline_run_id, user_id) REFERENCES keyword_benchmark_runs(id, user_id) DEFERRABLE INITIALLY DEFERRED,
  CHECK((kind = 'baseline' AND baseline_run_id IS NULL) OR (kind = 'fresh' AND baseline_run_id IS NOT NULL)),
  CHECK(session_id IS NULL OR create_attempt_at IS NOT NULL),
  CHECK(status <> 'completed' OR (answer_json IS NOT NULL AND session_id IS NOT NULL))
);

CREATE TABLE website_crawl_pages (
 id TEXT PRIMARY KEY, grant_id TEXT NOT NULL REFERENCES website_crawl_grants(id) DEFERRABLE INITIALLY DEFERRED,
 user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED, url TEXT NOT NULL,
 status TEXT NOT NULL, page_json TEXT, created_at BIGINT NOT NULL,
 UNIQUE(grant_id,url)
);

CREATE TABLE website_crawl_reviews (
 d1_rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
 id TEXT PRIMARY KEY, grant_id TEXT NOT NULL UNIQUE REFERENCES website_crawl_grants(id) DEFERRABLE INITIALLY DEFERRED,
 user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED, status TEXT NOT NULL,
 model TEXT NOT NULL, input_tokens BIGINT, output_tokens BIGINT, latency_ms BIGINT,
 result_json TEXT, created_at BIGINT NOT NULL, updated_at BIGINT NOT NULL
);

CREATE TABLE public_keyword_observations (
  run_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  revision BIGINT NOT NULL CHECK (revision > 0),
  payload_json TEXT,
  updated_at TEXT NOT NULL,
  PRIMARY KEY (run_id, user_id),
  FOREIGN KEY (run_id, user_id) REFERENCES keyword_benchmark_runs(id, user_id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  CHECK (payload_json IS NULL OR d1_json_valid(payload_json))
);

CREATE TABLE sandbox_seo_grants (
  id TEXT PRIMARY KEY NOT NULL,
  user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  run_id TEXT NOT NULL UNIQUE REFERENCES keyword_benchmark_runs(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  token_hash TEXT NOT NULL UNIQUE,
  domain TEXT NOT NULL,
  expires_at BIGINT NOT NULL,
  created_at BIGINT NOT NULL
, tool_version BIGINT NOT NULL DEFAULT 1);

CREATE TABLE keyword_research_requests (
 d1_rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
 id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
 grant_id TEXT REFERENCES sandbox_seo_grants(id) DEFERRABLE INITIALLY DEFERRED, domain TEXT NOT NULL,
 request_hash TEXT NOT NULL, request_key_hash TEXT NOT NULL,
 status TEXT NOT NULL DEFAULT 'pending', result_json TEXT, cost_micros BIGINT,
 created_at BIGINT NOT NULL, updated_at BIGINT NOT NULL,
 UNIQUE(user_id,request_key_hash), CHECK(cost_micros IS NULL OR cost_micros>=0)
);

CREATE TABLE d1_migrations (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name TEXT UNIQUE,
 applied_at TEXT
);

CREATE INDEX account_user_id_idx ON account(user_id);

CREATE INDEX agent_api_keys_owner ON agent_api_keys(user_id,created_at DESC);

CREATE INDEX agent_api_requests_owner_run ON agent_api_requests(user_id,resource_kind,run_id);

CREATE INDEX agent_tool_calls_owner_idx ON agent_tool_calls(user_id, created_at DESC);

CREATE INDEX evaluation_runs_background_active_idx
  ON evaluation_runs(background_checked_at, created_at, id)
  WHERE mode = 'live' AND deleted_at IS NULL AND status IN ('queued', 'running', 'requires_action');

CREATE UNIQUE INDEX evaluation_runs_one_active_per_user_idx
  ON evaluation_runs(user_id) WHERE status IN ('queued', 'running', 'requires_action');

CREATE INDEX evaluation_runs_user_created_idx ON evaluation_runs(user_id, created_at DESC);

CREATE INDEX evaluation_runs_user_status_idx ON evaluation_runs(user_id, status);

CREATE INDEX keyword_benchmark_cases_owner_suite ON keyword_benchmark_cases(user_id, suite_id, created_at, id);

CREATE INDEX keyword_benchmark_runs_owner_case ON keyword_benchmark_runs(user_id, case_id, created_at DESC);

CREATE INDEX keyword_benchmark_runs_owner_created ON keyword_benchmark_runs(user_id, created_at DESC, id);

CREATE INDEX keyword_benchmark_runs_owner_status ON keyword_benchmark_runs(user_id, status);

CREATE INDEX keyword_benchmark_suites_owner ON keyword_benchmark_suites(user_id, created_at DESC);

CREATE INDEX keyword_research_grant ON keyword_research_requests(grant_id);

CREATE INDEX keyword_research_owner_time ON keyword_research_requests(user_id,created_at);

CREATE INDEX provider_cost_owner ON provider_cost_observations(user_id,source,source_id,id DESC);

CREATE INDEX scans_site_created_idx ON scans(site_id, created_at DESC);

CREATE INDEX scans_user_created_idx ON scans(user_id, created_at DESC);

CREATE INDEX search_console_reports_owner_created ON search_console_reports(user_id, created_at DESC);

CREATE INDEX seo_reports_owner_created
  ON seo_reports (user_id, created_at DESC, id DESC);

CREATE INDEX session_user_id_idx ON session(user_id);

CREATE INDEX sites_user_id_idx ON sites(user_id);

CREATE INDEX typesafe_review_quota ON typesafe_reviews(user_id,created_at);

CREATE INDEX typesafe_tool_daily ON typesafe_tool_calls(user_id,created_at);

CREATE INDEX verification_identifier_idx ON verification(identifier);
-- SQLite-compatible read functions for the *bounded* JSON paths used by D1 callers.
-- JSON strings stay TEXT; missing paths and JSON null return SQL NULL.
CREATE FUNCTION json_extract(doc text, path text) RETURNS text LANGUAGE sql IMMUTABLE AS $$
 SELECT CASE WHEN jsonb_typeof(doc::jsonb #> string_to_array(trim(leading '$.' FROM path),'.')) IN ('object','array')
   THEN (doc::jsonb #> string_to_array(trim(leading '$.' FROM path),'.'))::text
   ELSE doc::jsonb #>> string_to_array(trim(leading '$.' FROM path),'.') END
$$;
CREATE FUNCTION json_type(doc text, path text) RETURNS text LANGUAGE sql IMMUTABLE AS $$
 SELECT CASE jsonb_typeof(doc::jsonb #> string_to_array(trim(leading '$.' FROM path),'.'))
 WHEN 'number' THEN CASE WHEN json_extract(doc,path) ~ '^-?[0-9]+$' THEN 'integer' ELSE 'real' END
 WHEN 'boolean' THEN CASE WHEN json_extract(doc,path)='true' THEN 'true' ELSE 'false' END
 ELSE jsonb_typeof(doc::jsonb #> string_to_array(trim(leading '$.' FROM path),'.')) END
$$;
CREATE FUNCTION json_each(doc text, path text DEFAULT '$') RETURNS TABLE(value text) LANGUAGE sql IMMUTABLE AS $$
 SELECT CASE WHEN jsonb_typeof(x.v) IN ('array','object') THEN x.v::text ELSE x.v #>> '{}' END
 FROM jsonb_each(CASE WHEN jsonb_typeof(doc::jsonb #> string_to_array(trim(leading '$.' FROM path),'.'))='object'
   THEN doc::jsonb #> string_to_array(trim(leading '$.' FROM path),'.') ELSE '{}'::jsonb END) x(key,v)
 UNION ALL
 SELECT CASE WHEN jsonb_typeof(y.v) IN ('array','object') THEN y.v::text ELSE y.v #>> '{}' END
 FROM jsonb_array_elements(CASE WHEN jsonb_typeof(doc::jsonb #> string_to_array(trim(leading '$.' FROM path),'.'))='array'
   THEN doc::jsonb #> string_to_array(trim(leading '$.' FROM path),'.') ELSE '[]'::jsonb END) y(v)
$$;
-- Supported SQLite form: strftime('%Y-%m-%d', epoch_ms/1000, 'unixepoch').
CREATE FUNCTION strftime(fmt text, epoch_seconds double precision, modifier text) RETURNS text LANGUAGE plpgsql STABLE AS $$
BEGIN
 IF modifier <> 'unixepoch' THEN RAISE EXCEPTION 'Unsupported strftime modifier'; END IF;
 IF fmt = '%Y-%m-%d' THEN RETURN to_char(to_timestamp(epoch_seconds) AT TIME ZONE 'UTC','YYYY-MM-DD'); END IF;
 IF fmt = '%Y-%m' THEN RETURN to_char(to_timestamp(epoch_seconds) AT TIME ZONE 'UTC','YYYY-MM'); END IF;
 IF fmt = '%Y-%m-%dT%H:%M:%fZ' THEN RETURN to_char(to_timestamp(epoch_seconds) AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'); END IF;
 RAISE EXCEPTION 'Unsupported strftime format';
END $$;

CREATE FUNCTION folio_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF current_setting('folio.importing',true)='on' THEN RETURN NEW; END IF;
 IF TG_TABLE_NAME='agent_api_requests' THEN
   IF (to_jsonb(NEW)-'disposition') IS DISTINCT FROM (to_jsonb(OLD)-'disposition')
      OR NOT (OLD.disposition='started' AND NEW.disposition='denied') THEN RAISE EXCEPTION 'API request identities and saved outcomes are immutable'; END IF;
 ELSIF TG_TABLE_NAME IN ('seo_agent_requests','provider_cost_observations') THEN
   RAISE EXCEPTION 'Append-only observation / request';
 ELSIF TG_TABLE_NAME='keyword_benchmark_runs' THEN
   IF ROW(NEW.id,NEW.user_id,NEW.suite_id,NEW.case_id,NEW.kind,NEW.baseline_run_id,NEW.model,
       NEW.harness_version,NEW.environment_type,NEW.environment_fingerprint,NEW.case_json,NEW.created_at,
       NEW.allowed_domains_json,NEW.deadline_at) IS DISTINCT FROM
      ROW(OLD.id,OLD.user_id,OLD.suite_id,OLD.case_id,OLD.kind,OLD.baseline_run_id,OLD.model,
       OLD.harness_version,OLD.environment_type,OLD.environment_fingerprint,OLD.case_json,OLD.created_at,
       OLD.allowed_domains_json,OLD.deadline_at)
      OR (OLD.session_id IS NOT NULL AND NEW.session_id IS DISTINCT FROM OLD.session_id)
      OR (OLD.create_attempt_at IS NOT NULL AND NEW.create_attempt_at IS DISTINCT FROM OLD.create_attempt_at)
      OR (OLD.cancel_attempt_at IS NOT NULL AND NEW.cancel_attempt_at IS DISTINCT FROM OLD.cancel_attempt_at)
      OR (OLD.cancel_acknowledged_at IS NOT NULL AND NEW.cancel_acknowledged_at IS DISTINCT FROM OLD.cancel_acknowledged_at)
      THEN RAISE EXCEPTION 'Benchmark inputs and lifecycle are immutable'; END IF;
   IF NEW.hold_release_at IS DISTINCT FROM OLD.hold_release_at OR NEW.hold_release_reason IS DISTINCT FROM OLD.hold_release_reason THEN
     IF OLD.hold_release_at IS NOT NULL OR OLD.hold_release_reason IS NOT NULL OR NEW.hold_release_at IS NULL
        OR NEW.hold_release_at < OLD.updated_at OR NEW.hold_release_reason IS DISTINCT FROM 'owner-acknowledged-unknown-creation-cost'
        OR OLD.status <> 'requires_action' OR OLD.session_id IS NOT NULL OR OLD.create_attempt_at IS NULL
        OR OLD.answer_json IS NOT NULL OR NEW.status IS DISTINCT FROM OLD.status OR NEW.session_id IS DISTINCT FROM OLD.session_id
        OR NEW.answer_json IS DISTINCT FROM OLD.answer_json OR NEW.usage_json IS DISTINCT FROM OLD.usage_json
        OR NEW.provider_metadata_json IS DISTINCT FROM OLD.provider_metadata_json OR NEW.error IS DISTINCT FROM OLD.error
        OR NEW.revision <> OLD.revision+1 OR NEW.updated_at IS DISTINCT FROM NEW.hold_release_at
     THEN RAISE EXCEPTION 'Hold release acknowledgement is invalid or immutable'; END IF;
   END IF;
   IF NEW.archived_at IS DISTINCT FROM OLD.archived_at THEN
     IF OLD.archived_at IS NOT NULL OR NEW.archived_at IS NULL OR OLD.status <> 'requires_action'
        OR OLD.create_attempt_at IS NULL OR OLD.answer_json IS NOT NULL OR NEW.archived_at < OLD.created_at+86400000
        OR (OLD.session_id IS NOT NULL AND OLD.cancel_attempt_at IS NULL)
        OR NEW.status IS DISTINCT FROM OLD.status OR NEW.session_id IS DISTINCT FROM OLD.session_id
        OR NEW.answer_json IS DISTINCT FROM OLD.answer_json OR NEW.usage_json IS DISTINCT FROM OLD.usage_json
        OR NEW.provider_metadata_json IS DISTINCT FROM OLD.provider_metadata_json OR NEW.error IS DISTINCT FROM OLD.error
        OR NEW.revision <> OLD.revision+1 OR NEW.updated_at IS DISTINCT FROM NEW.archived_at
     THEN RAISE EXCEPTION 'Archive requires an old unresolved attempt and retains accounting'; END IF;
   END IF;
   IF OLD.status IN ('completed','failed','cancelled') AND
     (OLD.session_id IS NULL OR NEW.status IS DISTINCT FROM OLD.status OR NEW.answer_json IS DISTINCT FROM OLD.answer_json
      OR NEW.provider_metadata_json IS DISTINCT FROM OLD.provider_metadata_json OR NEW.error IS DISTINCT FROM OLD.error
      OR NEW.cancel_attempt_at IS DISTINCT FROM OLD.cancel_attempt_at OR NEW.cancel_acknowledged_at IS DISTINCT FROM OLD.cancel_acknowledged_at
      OR NEW.hold_release_at IS DISTINCT FROM OLD.hold_release_at OR NEW.hold_release_reason IS DISTINCT FROM OLD.hold_release_reason
      OR NEW.archived_at IS DISTINCT FROM OLD.archived_at OR NEW.revision <> OLD.revision+1 OR NEW.updated_at < OLD.updated_at
      OR NOT d1_json_valid(NEW.usage_json)) THEN RAISE EXCEPTION 'Terminal benchmark observations are immutable'; END IF;
 END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER agent_api_request_immutable BEFORE UPDATE ON agent_api_requests FOR EACH ROW EXECUTE FUNCTION folio_guard();
CREATE TRIGGER seo_agent_request_immutable BEFORE UPDATE ON seo_agent_requests FOR EACH ROW EXECUTE FUNCTION folio_guard();
CREATE TRIGGER provider_cost_append_only BEFORE UPDATE ON provider_cost_observations FOR EACH ROW EXECUTE FUNCTION folio_guard();
CREATE TRIGGER keyword_benchmark_run_frozen_input BEFORE UPDATE ON keyword_benchmark_runs FOR EACH ROW EXECUTE FUNCTION folio_guard();
CREATE FUNCTION keyword_insert_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF current_setting('folio.importing',true) IS DISTINCT FROM 'on' AND
   (NEW.hold_release_at IS NOT NULL OR NEW.hold_release_reason IS NOT NULL OR NEW.archived_at IS NOT NULL)
 THEN RAISE EXCEPTION 'Hold release / archive requires an existing unresolved attempt'; END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER keyword_insert_guard BEFORE INSERT ON keyword_benchmark_runs FOR EACH ROW EXECUTE FUNCTION keyword_insert_guard();

CREATE FUNCTION erase_evaluation_evidence() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF TG_OP='DELETE' THEN
   UPDATE typesafe_reviews SET result_json=NULL WHERE user_id=OLD.user_id AND run_id=OLD.id;
   RETURN OLD;
 END IF;
 IF NEW.deleted_at IS NOT NULL THEN
   DELETE FROM agent_tool_calls WHERE run_id=NEW.id;
   UPDATE typesafe_reviews SET result_json=NULL WHERE user_id=NEW.user_id AND run_id=NEW.id;
   DELETE FROM website_crawl_pages WHERE grant_id IN (SELECT id FROM website_crawl_grants WHERE run_id=NEW.id);
   UPDATE website_crawl_reviews SET result_json=NULL WHERE grant_id IN (SELECT id FROM website_crawl_grants WHERE run_id=NEW.id);
   UPDATE website_crawl_grants SET target_url='', expires_at=0 WHERE run_id=NEW.id;
 END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER erase_deleted_evaluation_evidence AFTER UPDATE OF deleted_at ON evaluation_runs
 FOR EACH ROW WHEN (NEW.deleted_at IS NOT NULL) EXECUTE FUNCTION erase_evaluation_evidence();
CREATE TRIGGER erase_deleted_evaluation_source AFTER DELETE ON evaluation_runs
 FOR EACH ROW EXECUTE FUNCTION erase_evaluation_evidence();

-- Historical rates belong to the D1 export; do not seed newer prices here.
-- Observations are cumulative snapshots, not chargeable invoices.
CREATE FUNCTION folio_cost_snapshot() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE src text; rev bigint; prov text; mdl text; stat text; inp bigint; cached bigint; outp bigint;
 known bigint; complete bigint := 0; rate provider_cost_rates%ROWTYPE; estimate bigint; payload jsonb;
BEGIN
 IF current_setting('folio.importing',true)='on' THEN RETURN NEW; END IF;
 IF TG_TABLE_NAME='keyword_benchmark_runs' THEN
   IF TG_OP='UPDATE' AND NEW.usage_json IS NOT DISTINCT FROM OLD.usage_json AND NEW.status IS NOT DISTINCT FROM OLD.status THEN RETURN NEW; END IF;
   src:='keyword'; rev:=NEW.revision; prov:='openai'; mdl:=NEW.model; stat:=NEW.status;
   payload:=NEW.usage_json::jsonb;
   IF jsonb_typeof(payload->'inputTokens')='number' AND (payload->>'inputTokens') ~ '^[0-9]{1,13}$' THEN inp:=(payload->>'inputTokens')::bigint; END IF;
   IF jsonb_typeof(payload->'cachedInputTokens')='number' AND (payload->>'cachedInputTokens') ~ '^[0-9]{1,13}$' THEN cached:=(payload->>'cachedInputTokens')::bigint; END IF;
   IF jsonb_typeof(payload->'outputTokens')='number' AND (payload->>'outputTokens') ~ '^[0-9]{1,13}$' THEN outp:=(payload->>'outputTokens')::bigint; END IF;
 ELSIF TG_TABLE_NAME='evaluation_runs' THEN
   IF NEW.mode <> 'live' OR NEW.deleted_at IS NOT NULL THEN RETURN NEW; END IF;
   IF TG_OP='UPDATE' AND (NEW.result_json::jsonb->'usage') IS NOT DISTINCT FROM (OLD.result_json::jsonb->'usage')
     AND NEW.status IS NOT DISTINCT FROM OLD.status THEN RETURN NEW; END IF;
   src:='evaluation'; rev:=NEW.revision; prov:='openai'; payload:=NEW.result_json::jsonb; mdl:=payload->>'model'; stat:=NEW.status;
   IF (payload#>>'{usage,input_tokens}') ~ '^[0-9]{1,13}$' THEN inp:=(payload#>>'{usage,input_tokens}')::bigint; END IF;
   IF (payload#>>'{usage,input_tokens_details,cached_tokens}') ~ '^[0-9]{1,13}$' THEN cached:=(payload#>>'{usage,input_tokens_details,cached_tokens}')::bigint; END IF;
   IF (payload#>>'{usage,output_tokens}') ~ '^[0-9]{1,13}$' THEN outp:=(payload#>>'{usage,output_tokens}')::bigint; END IF;
 ELSE
   IF TG_OP='UPDATE' AND NEW.result_json IS NOT DISTINCT FROM OLD.result_json THEN RETURN NEW; END IF;
   src:='seo'; rev:=coalesce(NEW.retrieved_at,0); prov:='dataforseo'; payload:=NEW.result_json::jsonb;
   stat:=coalesce(payload->>'status','unconfirmed');
   IF (payload->>'totalCostUsd') ~ '^[0-9]+(\.[0-9]+)?$' AND (payload->>'totalCostUsd')::numeric <= 1000000 THEN
     known:=round((payload->>'totalCostUsd')::numeric*1000000)::bigint;
     IF payload->>'costIsComplete' IN ('true','1') THEN complete:=1; END IF;
   ELSIF (payload->>'knownCostUsd') ~ '^[0-9]+(\.[0-9]+)?$' AND (payload->>'knownCostUsd')::numeric <= 1000000
      AND (jsonb_typeof(payload#>'{organic,costUsd}')='number' OR jsonb_typeof(payload#>'{backlinks,costUsd}')='number') THEN
     known:=round((payload->>'knownCostUsd')::numeric*1000000)::bigint;
   END IF;
 END IF;
 IF inp > 1000000000000 OR cached > 1000000000000 OR outp > 1000000000000 THEN inp:=NULL; cached:=NULL; outp:=NULL; END IF;
 SELECT * INTO rate FROM provider_cost_rates WHERE model=mdl;
 IF inp IS NOT NULL AND outp IS NOT NULL AND rate.model IS NOT NULL AND (cached IS NULL OR cached<=inp) THEN
   estimate:=round((inp-coalesce(cached,0))*rate.input_usd_per_million::numeric + coalesce(cached,0)*rate.cached_usd_per_million::numeric + outp*rate.output_usd_per_million::numeric)::bigint;
 END IF;
 INSERT INTO provider_cost_observations(user_id,source,source_id,source_revision,provider,model,status,source_created_at,observed_at,
 input_tokens,cached_input_tokens,output_tokens,estimated_token_micros,reported_known_micros,reported_complete,rate_version)
 VALUES(NEW.user_id,src,NEW.id,rev,prov,mdl,stat,NEW.created_at,(extract(epoch from clock_timestamp())*1000)::bigint,
 inp,cached,outp,estimate,known,complete,rate.version) ON CONFLICT DO NOTHING;
 RETURN NEW;
END $$;
CREATE TRIGGER cost_keyword_insert AFTER INSERT ON keyword_benchmark_runs FOR EACH ROW EXECUTE FUNCTION folio_cost_snapshot();
CREATE TRIGGER cost_keyword_update AFTER UPDATE ON keyword_benchmark_runs FOR EACH ROW EXECUTE FUNCTION folio_cost_snapshot();
CREATE TRIGGER cost_evaluation_insert AFTER INSERT ON evaluation_runs FOR EACH ROW EXECUTE FUNCTION folio_cost_snapshot();
CREATE TRIGGER cost_evaluation_update AFTER UPDATE ON evaluation_runs FOR EACH ROW EXECUTE FUNCTION folio_cost_snapshot();
CREATE TRIGGER cost_seo_insert AFTER INSERT ON seo_reports FOR EACH ROW EXECUTE FUNCTION folio_cost_snapshot();
CREATE TRIGGER cost_seo_update AFTER UPDATE ON seo_reports FOR EACH ROW EXECUTE FUNCTION folio_cost_snapshot();

CREATE VIEW provider_cost_latest AS
 SELECT o.* FROM provider_cost_observations o WHERE o.id=(SELECT max(n.id) FROM provider_cost_observations n
 WHERE n.user_id=o.user_id AND n.source=o.source AND n.source_id=o.source_id)
 UNION ALL SELECT d1_rowid,user_id,'semantic-review',id,source_revision,'typesafe',model,status,created_at,updated_at,input_tokens,NULL,output_tokens,NULL,NULL,0,NULL FROM typesafe_reviews
 UNION ALL SELECT id,user_id,'agent-semantic-tool',id::text,0,'typesafe',model,status,created_at,updated_at,input_tokens,NULL,output_tokens,NULL,NULL,0,NULL FROM typesafe_tool_calls
 UNION ALL SELECT d1_rowid,user_id,'crawl-semantic-review',id,0,'typesafe',model,status,created_at,updated_at,input_tokens,NULL,output_tokens,NULL,NULL,0,NULL FROM website_crawl_reviews
 UNION ALL SELECT d1_rowid,user_id,'keyword-research',id,0,'dataforseo',NULL,status,created_at,updated_at,NULL,NULL,NULL,NULL,cost_micros,CASE WHEN cost_micros IS NULL THEN 0 ELSE 1 END,NULL FROM keyword_research_requests;
