"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowDown, ArrowRight, Copy, FileCode2 } from "lucide-react";
import { AGENT_API_ENDPOINTS } from "@/lib/agent-api-reference";
import { AgentApiKeys } from "./agent-api-keys";
import "./agent-api-reference.css";

export function AgentApiReference() {
  const [selected, setSelected] = useState<string>("ensure");
  const [language, setLanguage] = useState("curl");
  const [notice, setNotice] = useState("");
  const endpoint = AGENT_API_ENDPOINTS.find(value => value.id === selected)!;
  const path = endpoint.path.replace("{kind}", "keyword").replace("{id}", "run_example") + ("query" in endpoint ? endpoint.query : "");
  const body = "body" in endpoint ? JSON.stringify(endpoint.body, null, 2) : undefined;
  const snippet = language === "curl" ? `curl ${endpoint.method === "GET" ? "" : "-X POST "}"$FOLIO_BASE_URL/api/v1${path}" \\\n  -H "Authorization: Bearer $FOLIO_API_KEY"${body ? ` \\\n  -H "Content-Type: application/json"` : ""}${(endpoint.id === "ensure" || endpoint.id === "seo-lookup") ? ` \\\n  -H "Idempotency-Key: research-request-001"` : ""}${body ? ` \\\n  --data '${body}'` : ""}` : `const response = await fetch(\`\${process.env.FOLIO_BASE_URL}/api/v1${path}\`, {\n  method: "${endpoint.method}",\n  headers: {\n    Authorization: \`Bearer \${process.env.FOLIO_API_KEY}\`,${body ? '\n    "Content-Type": "application/json",' : ""}${(endpoint.id === "ensure" || endpoint.id === "seo-lookup") ? '\n    "Idempotency-Key": "research-request-001",' : ""}\n  },${body ? `\n  body: JSON.stringify(${body}),` : ""}\n});\nconst result = await response.json();\nif (!response.ok) throw new Error(result.error.message);`;
  return <div className="api-docs"><header className="api-docs-header"><Link className="api-wordmark" href="/">folio.</Link><span>Agent API</span><Link href="/evaluations">Open workspace <ArrowRight size={14} /></Link></header>
    <div className="api-docs-layout"><nav className="api-docs-nav" aria-label="API reference navigation"><a href="#api-overview">Overview</a><a href="#api-keys">API keys</a><a href="#api-mcp">Codex & Claude Code</a><a href="#api-freshness">Freshness & runs</a><strong>Reference</strong>{AGENT_API_ENDPOINTS.map(item => <a key={item.id} href="#api-endpoint" aria-current={selected === item.id ? "true" : undefined} onClick={() => setSelected(item.id)}><span className={`api-method ${item.method.toLowerCase()}`}>{item.method}</span>{item.title}</a>)}<a href="#api-errors">Errors & limits</a></nav>
    <main className="api-docs-main"><section id="api-overview"><h1>Folio Agent API</h1><p className="api-lead">Read saved website checks and search observations. Reuse recent results or request a new evaluation through one API.</p><div className="api-doc-links"><a href="/api/openapi.json"><FileCode2 size={15} />OpenAPI schema</a><a href="/docs/api/reference.md">Markdown for agents <ArrowRight size={14} /></a><a href="/llms.txt">llms.txt</a></div><p>Use <code>/api/v1</code> on this Folio server. Locally, set <code>FOLIO_BASE_URL=http://localhost:3001</code>. Use your deployed HTTPS origin after production setup.</p><p>Send a Folio key in <code>Authorization: Bearer &lt;FOLIO_API_KEY&gt;</code>. Each key accesses only its owner’s workspace.</p></section>
    <section id="api-mcp"><h2>Connect your coding agent</h2><p>Use Folio’s authenticated MCP server to inspect your website, read search evidence, and plan changes in Codex or Claude Code. Create a key below and keep it in the client’s environment as <code>FOLIO_API_KEY</code>.</p><p>Endpoint: <code>https://usefolio.site/api/mcp</code>. Use <code>http://localhost:3001/api/mcp</code> when connecting a local coding client to local Folio.</p><h3>Codex</h3><pre><code>{'[mcp_servers.folio]\nurl = "https://usefolio.site/api/mcp"\nbearer_token_env_var = "FOLIO_API_KEY"'}</code></pre><h3>Claude Code</h3><pre><code>{JSON.stringify({mcpServers:{folio:{type:"http",url:"https://usefolio.site/api/mcp",headers:{Authorization:"Bearer ${FOLIO_API_KEY}"}}}},null,2)}</code></pre><p>Start with: “Use Folio to inspect my website’s saved SEO and visibility evidence, then propose changes in this repository.” Saved reports use <code>read</code>; new evaluations need <code>evaluate</code>; fresh DataForSEO lookups need <code>seo</code>. The client can edit your local code using its own tools.</p><p>In keyword run settings, enable search and backlinks to authorize one SEO lookup for the selected website. Repeated sandbox tool calls reuse the report. This needs a deployed public endpoint configured on Folio.</p></section>
    <section id="api-freshness"><h2>Freshness and run status</h2><p>The default freshness window is <strong>24 hours</strong>. Override <code>maxAgeSeconds</code> per request, from 0 to 604800.</p><div className="api-flow" aria-label="Observation request flow"><div><strong>Request observation</strong><span>POST with the saved website or question ID</span></div><ArrowDown size={17}/><div><strong>Check saved evidence</strong><span>Matching result within 24 hours?</span></div><div className="api-flow-branches"><div><strong>Yes · return it</strong><span>No new evaluation</span></div><div><strong>No · start a run</strong><span>Or reuse matching active work</span></div></div></div><p><code>GET</code> only reads saved data. <code>POST /observations/ensure</code> can start paid work and needs the <code>evaluate</code> permission. Reuse the same <code>Idempotency-Key</code> and body when retrying; changing the key is a new request.</p><p>A <code>202</code> response points to the saved run. Read its <code>pollUrl</code>, and use <code>/reconcile</code> to retrieve existing remote progress. A cancelled or failed attempt stays in history. Replaying frozen website evidence does not make its capture newer.</p></section>
    <section id="api-endpoint"><div className="api-endpoint-heading"><span className={`api-method ${endpoint.method.toLowerCase()}`}>{endpoint.method}</span><code>/api/v1{endpoint.path}</code></div><h2>{endpoint.title}</h2><p>{endpoint.description}</p><p className="api-small">Required permission: <code>{endpoint.scope}</code></p><div className="api-example-grid"><div><div className="api-code-heading"><h3>Request</h3><label className="sr-only" htmlFor="api-example-language">Example language</label><select id="api-example-language" value={language} onChange={event => setLanguage(event.target.value)}><option value="curl">cURL</option><option value="javascript">JavaScript</option></select><button aria-label="Copy request example" onClick={() => { void navigator.clipboard.writeText(snippet).then(() => setNotice("Request example copied.")).catch(() => setNotice("Select the example to copy it.")); }}><Copy size={14}/></button></div><pre><code>{snippet}</code></pre></div><div><div className="api-code-heading"><h3>Response structure</h3><span>Illustrative excerpt</span></div><pre><code>{JSON.stringify(endpoint.response, null, 2)}</code></pre></div></div>{notice && <p role="status">{notice}</p>}
    {endpoint.id === "ensure" || endpoint.id === "read" ? <table className="api-parameters"><caption>Observation parameters</caption><thead><tr><th>Parameter</th><th>Meaning</th></tr></thead><tbody><tr><td><code>kind</code></td><td><code>website</code> for captured-page checks, or <code>keyword</code> for search recommendations.</td></tr><tr><td><code>websiteId / caseId</code></td><td>Use the corresponding ID returned by your owned websites or benchmark-cases list. Send exactly one.</td></tr><tr><td><code>maxAgeSeconds</code></td><td>Defaults to 86400. Only a completed matching observation can be fresh.</td></tr></tbody></table> : null}
    <details className="api-contract"><summary>Reading outcomes and progress</summary><dl><div><dt>fresh_saved</dt><dd>A saved result meets the requested age and configuration.</dd></div><div><dt>existing_active / started</dt><dd>Follow the saved run. Neither means that verification passed.</dd></div><div><dt>missing</dt><dd>No matching result exists. Read requests never create one.</dd></div><div><dt>requires_action</dt><dd>Inspect the existing attempt. Do not automatically create a replacement.</dd></div><div><dt>completed / failed / cancelled</dt><dd>Recorded terminal states. Read the checks and coverage, not just the status.</dd></div></dl></details></section>
    <section id="api-keys"><h2>API keys</h2><p>Create a read key for saved evidence, or allow explicit evaluation requests. The key is shown once; only its hash is stored.</p><AgentApiKeys /></section>
    <section id="api-errors"><h2>Errors and limits</h2><p>Failures return <code>{'{"error":{"code":"…","message":"…"}}'}</code>. Keep unknown measurements and costs as <code>null</code>.</p><dl className="api-errors"><div><dt>401 / 403</dt><dd>Check the key’s lifetime, permissions, and account access.</dd></div><div><dt>404</dt><dd>The record is unavailable to this key’s owner.</dd></div><div><dt>409</dt><dd>Inspect the existing request or active run. Never retry ambiguous creation with a new key.</dd></div><div><dt>429</dt><dd>Keys allow 60 requests per minute. Honor <code>Retry-After</code> when supplied. Evaluation allowances also apply; denied requests keep their idempotency outcome.</dd></div><div><dt>503</dt><dd>Retrieve existing state before deciding whether to retry.</dd></div></dl><p>Search recommendation positions describe the saved answer for a particular question. Page verification checks measure captured evidence. They remain separate in API responses.</p></section></main></div></div>;
}
