"use client";
import { useSearchParams } from 'next/navigation';
import { useState } from 'react';
import Link from 'next/link';
import { PUBLIC_SEARCH_QUERIES, PUBLIC_SEARCH_OBSERVATIONS, PUBLIC_CORE_QUERIES } from '@/lib/public-search-rankings';
import { websiteOverview } from '@/lib/website-landscape';
import { LANDSCAPE_MODELS } from '@/lib/model-landscape';
import './model-landscape.css';
const core=PUBLIC_CORE_QUERIES;
const audienceNames=[...new Set(core.map(q=>q.audience))];
export function ModelLandscape() {
 const params=useSearchParams(), [search,setSearch]=useState(''), [limit,setLimit]=useState(12);
 const selected=params.get('model')??'', audience=params.get('landscapeAudience')??'';
 const query=PUBLIC_SEARCH_QUERIES.find(q=>q.id===params.get('query'));
 const questions=query?[query]:core.filter(q=>!audience||q.audience===audience);
 const models=LANDSCAPE_MODELS.filter(m=>!selected||selected===m.id);
 const result=websiteOverview(PUBLIC_SEARCH_OBSERVATIONS,questions.map(q=>q.id),models.map(m=>m.id));
 const {rows,answers,coverage}=result;
 const active=rows.find(r=>r.domain===params.get('site'));
 const set=(changes:Record<string,string>)=>{const next=new URLSearchParams(params.toString());for(const [key,value] of Object.entries(changes)){if(value)next.set(key,value);else next.delete(key);}window.history.pushState(null,'',`${window.location.pathname}?${next}`);};
 const maximum=Math.max(5,...rows.map(r=>Math.ceil(r.position)));
 const shareMax=query?100:Math.max(10,Math.ceil(Math.max(0,...rows.map(r=>r.share))/10)*10);
 const x=(share:number)=>66+share/shareMax*532;
 const y=(position:number)=>62+(position-1)/(maximum-1)*288;
 const labelled=[...rows.slice(0,7),...(active&&!rows.slice(0,7).includes(active)?[active]:[])].sort((a,b)=>a.position-b.position||b.share-a.share);
 const visible=rows.filter(r=>`${r.domain} ${r.name}`.toLowerCase().includes(search.toLowerCase()));
 const selectSite=(domain:string)=>set({site:active?.domain===domain?'':domain});
 return <section className="model-landscape website-landscape" aria-labelledby="landscape-title">
  <header className="landscape-heading"><div><p className="landscape-kicker">THE FOLIO INDEX / WEBSITE DISCOVERY</p><h2 id="landscape-title">Which websites<br/><em>get recommended?</em></h2><p className="landscape-intro">The websites AI research agents recommended in this saved cohort, across Astra 6 and Sol, Terra and Luna 5.6.</p></div><div className="landscape-cohort"><strong>{rows.length}</strong><span>websites in this view</span><p>{answers} saved {answers===1?'answer':'answers'} · {questions.length} {questions.length===1?'question':'questions'}</p></div></header>
  <div className="website-controls"><label>Explore<select aria-label="Website comparison audience" value={audience} onChange={e=>set({landscapeAudience:e.target.value,query:'',site:''})}><option value="">All website categories</option>{audienceNames.map(a=><option key={a}>{a}</option>)}</select></label><label>Answers from<select aria-label="Website comparison model" value={selected} onChange={e=>set({model:e.target.value,site:''})}><option value="">Average across models</option>{LANDSCAPE_MODELS.map(m=><option key={m.id} value={m.id}>{m.label}</option>)}</select></label></div>
  <label className="website-question-select">Question<select aria-label="Website comparison question" value={query?.id??''} onChange={e=>set({query:e.target.value,site:''})}><option value="">All {core.filter(q=>!audience||q.audience===audience).length} core questions</option>{query&&!core.some(q=>q.id===query.id)&&<option value={query.id}>{query.query}</option>}{core.filter(q=>!audience||q.audience===audience||q.id===query?.id).map(q=><option key={q.id} value={q.id}>{q.query}</option>)}</select></label>
  {query&&<p className="website-question">{query.query} <button className="website-reset" onClick={()=>set({query:'',landscapeAudience:'',site:''})}>Show all websites ↗</button></p>}
  <div className="website-coverage" aria-label="Saved answer coverage">{coverage.map(c=><span key={c.model}><i className={c.answers===c.planned?'complete':''}/><b>{LANDSCAPE_MODELS.find(m=>m.id===c.model)?.label}</b> {c.answers}/{c.planned} answers</span>)}</div>
  <div className="landscape-chart-heading"><h3>{selected?'Website recommendations':'Website averages across models'}</h3><span>Upper right: more frequent recommendations, earlier in the list</span></div>
  {!result.complete&&<p className="website-coverage-note">Partial coverage: {answers}/{questions.length*models.length} answers available. Averages use saved answers only; missing results are not zeroes.</p>}
  {rows.length ? <><div className="website-plot"><svg viewBox="0 0 900 420" role="img" aria-label="Website appearances and average recommendation position"><rect x="66" y="62" width="532" height="288" fill="#fbf8ee"/>{[0,1,2,3,4].map(i=>{const v=shareMax*i/4;return <g key={i}><line x1={x(v)} x2={x(v)} y1="62" y2="350" stroke="#d5d7c9"/><text x={x(v)} y="372" textAnchor="middle" className="landscape-tick">{v.toFixed(v%1?1:0)}%</text></g>})}{Array.from({length:5},(_,i)=>1+(maximum-1)*i/4).map(v=><g key={v}><line x1="66" x2="598" y1={y(v)} y2={y(v)} stroke="#d5d7c9" strokeDasharray="3 5"/><text x="53" y={y(v)+4} textAnchor="end" className="landscape-tick">{v.toFixed(v%1?1:0)}</text></g>)}<text x="332" y="406" textAnchor="middle" className="landscape-axis">{selected?'Appearance rate in saved answers':'Average appearance rate across models'}</text><text transform="translate(18 205) rotate(-90)" textAnchor="middle" className="landscape-axis">Average position · 1 is first</text>{rows.map(r=><g key={r.domain} className="website-dot" role="button" tabIndex={0} aria-label={`Inspect ${r.domain}, ${r.share.toFixed(1)} percent, position ${r.position.toFixed(1)}`} onClick={()=>selectSite(r.domain)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectSite(r.domain)}}}><circle cx={x(r.share)} cy={y(r.position)} r="14" fill="transparent"/><circle cx={x(r.share)} cy={y(r.position)} r={active?.domain===r.domain?9:5} fill={active?.domain===r.domain?'#987442':'#28543d'} opacity={active&&active.domain!==r.domain?.toString()?0.3:0.75} stroke="#fbf8ee" strokeWidth="1.5"/><title>{`${r.domain}: ${r.share.toFixed(1)}% average appearance, position ${r.position.toFixed(1)}`}</title></g>)}{labelled.map((r,i)=><g key={r.domain} className="website-chart-label" onClick={()=>selectSite(r.domain)}><path d={`M ${x(r.share)+8} ${y(r.position)} L 627 ${74+i*35}`} fill="none" stroke="#778c6c" opacity=".55"/><text x="638" y={78+i*35} className="landscape-label">{r.domain.length>28?`${r.domain.slice(0,26)}…`:r.domain}</text></g>)}</svg></div><p className="website-chart-help">Every dot is a website. Select a dot or website below to compare its model results. Labels highlight the most frequently recommended websites; the table includes all {rows.length}.</p>
  {active&&<aside className="website-detail" aria-label={`Model results for ${active.domain}`}><div><h3>{active.name}</h3><a href={active.url} target="_blank" rel="noreferrer">{active.domain} ↗</a><button aria-label="Close website details" onClick={()=>set({site:''})}>×</button></div><div className="website-model-breakdown">{active.perModel.map(m=><section key={m.model}><h4>{LANDSCAPE_MODELS.find(item=>item.id===m.model)?.label}</h4><strong>{m.share===null?'—':`${m.share.toFixed(1)}%`}</strong><p>{m.appearances}/{m.answers} saved answers</p><small>{m.position===null?'No recommendation position':`Avg. position ${m.position.toFixed(1)}`}</small>{m.queryId&&<Link href={`?query=${encodeURIComponent(m.queryId)}&model=${encodeURIComponent(m.model)}`}>See source answer ↗</Link>}</section>)}</div></aside>}
  <div className="website-table-heading"><h3>All websites <span>{rows.length}</span></h3><label><span className="sr-only">Find a website</span><input aria-label="Find a website" placeholder="Find a website…" value={search} onChange={e=>{setSearch(e.target.value);setLimit(12)}}/></label></div><div className="landscape-table-wrap website-results"><table><caption>{selected?'One model’s saved recommendations':'Each model has equal weight in the average'} · {questions.length} {questions.length===1?'question':'questions'}</caption><thead><tr><th>Website</th><th>Avg. appearance</th><th>Avg. position</th><th>Models recommending</th><th>Questions appearing in</th></tr></thead><tbody>{visible.slice(0,limit).map(r=><tr key={r.domain} aria-selected={active?.domain===r.domain}><th><button onClick={()=>selectSite(r.domain)}>{r.name} ↗</button><small>{r.domain}</small></th><td><span className="website-rate"><i style={{width:`${Math.max(2,r.share)}%`}}/>{r.share.toFixed(1)}%</span></td><td>{r.position.toFixed(1)}</td><td>{r.modelCount}/{result.measuredModels}</td><td>{r.questionCount}/{questions.length}</td></tr>)}</tbody></table>{visible.length>limit&&<button className="website-show-more" onClick={()=>setLimit(limit+12)}>Show more websites ({limit} of {visible.length}) ↓</button>}{!visible.length&&<p>No websites match “{search}”.</p>}</div></> : <p>No saved answer for this selection. This is unmeasured, not a zero score. <button className="website-reset" onClick={()=>set({model:''})}>View available models</button></p>}
  {result.firstDate&&<p className="landscape-note">Observed {result.firstDate}{result.lastDate!==result.firstDate?` — ${result.lastDate}`:''}. Latest published answer per model and question; collection dates can differ.</p>}
  <details className="landscape-details"><summary>How to read this comparison</summary><p>Uses the latest published answer for each question and model. For each model, appearance rate is the share of its saved answers recommending a website. We average those rates with equal weight per model. Average position is the mean of each recommending model’s average position; non-appearances have no position. Missing and failed answers are excluded, never scored as zero. Different coverage can affect averages.</p><p>This measures presence in the selected question set, not universal website quality. Some questions explicitly name websites, so compare within a relevant category or question. These are Folio managed research-agent results, not Google rankings or consumer ChatGPT measurements. Reviewed documentation aliases are grouped; other hostnames remain separate. Source questions, citations and returned reasons remain available below.</p></details>
  <p className="landscape-note"><a href="/leaderboard?view=questions">Explore earlier company-mention cohorts ↗</a></p>
 </section>;
}
