"use client";
import { useSearchParams } from 'next/navigation';
import { useState } from 'react';
import Link from 'next/link';
import { PUBLIC_SEARCH_QUERIES, PUBLIC_SEARCH_OBSERVATIONS, PUBLIC_CORE_QUERIES } from '@/lib/public-search-rankings';
import { websiteOverview } from '@/lib/website-landscape';
import { LANDSCAPE_MODELS } from '@/lib/model-landscape';
import { UiField } from './ui/primitives';
import { WebsiteSummaryChart } from './website-summary-chart';
import './model-landscape.css';
const core=PUBLIC_CORE_QUERIES;
const audienceNames=[...new Set(core.map(q=>q.audience))];
export function ModelLandscape() {
 const params=useSearchParams(), [search,setSearch]=useState(''), [limit,setLimit]=useState(12);
 const selected=params.get('model')??'', audience=params.get('landscapeAudience')??'';
 const query=PUBLIC_SEARCH_QUERIES.find(q=>q.id===params.get('query'));
 const questions=query?[query]:core.filter(q=>!audience||q.audience===audience);
 const models=LANDSCAPE_MODELS.filter(m=>!selected||selected===m.id);
 const result=websiteOverview(PUBLIC_SEARCH_OBSERVATIONS,questions.map(q=>q.id),models.map(m=>m.id));
 const {rows,answers,coverage}=result;
 const active=rows.find(r=>r.domain===params.get('site'));
 const set=(changes:Record<string,string>)=>{const next=new URLSearchParams(params.toString());for(const [key,value] of Object.entries(changes)){if(value)next.set(key,value);else next.delete(key);}window.history.pushState(null,'',`${window.location.pathname}?${next}`);};
 const shareMax=query?100:Math.max(10,Math.ceil(Math.max(0,...rows.map(r=>r.share))/10)*10);
 const chartRows=rows.slice(0,12);
 const visible=rows.filter(r=>`${r.domain} ${r.name}`.toLowerCase().includes(search.toLowerCase()));
 const selectSite=(domain:string)=>set({site:active?.domain===domain?'':domain});
 return <section className="model-landscape website-landscape" aria-labelledby="landscape-title">
  <header className="landscape-heading"><div><p className="landscape-kicker">THE FOLIO INDEX / WEBSITE DISCOVERY</p><h2 id="landscape-title">Which websites<br/><em>get recommended?</em></h2><p className="landscape-intro">The websites AI research agents recommended in this saved cohort, across Astra 6 and Sol, Terra and Luna 5.6.</p></div><div className="landscape-cohort"><strong>{rows.length}</strong><span>websites in this view</span><p>{answers} saved {answers===1?'answer':'answers'} · {questions.length} {questions.length===1?'question':'questions'}</p></div></header>
  <WebsiteSummaryChart rows={rows} shareMax={shareMax} selectedDomain={active?.domain}/>
  <div className="website-controls"><label>Explore<select aria-label="Website comparison audience" value={audience} onChange={e=>set({landscapeAudience:e.target.value,query:'',site:''})}><option value="">All website categories</option>{audienceNames.map(a=><option key={a}>{a}</option>)}</select></label><label>Answers from<select aria-label="Website comparison model" value={selected} onChange={e=>set({model:e.target.value,site:''})}><option value="">Average across models</option>{LANDSCAPE_MODELS.map(m=><option key={m.id} value={m.id}>{m.label}</option>)}</select></label></div>
  <label className="website-question-select">Question<select aria-label="Website comparison question" value={query?.id??''} onChange={e=>set({query:e.target.value,site:''})}><option value="">All {core.filter(q=>!audience||q.audience===audience).length} core questions</option>{query&&!core.some(q=>q.id===query.id)&&<option value={query.id}>{query.query}</option>}{core.filter(q=>!audience||q.audience===audience||q.id===query?.id).map(q=><option key={q.id} value={q.id}>{q.query}</option>)}</select></label>
  {query&&<p className="website-question">{query.query} <button className="website-reset" onClick={()=>set({query:'',landscapeAudience:'',site:''})}>Show all websites ↗</button></p>}
  <div className="website-coverage" aria-label="Saved answer coverage">{coverage.map(c=><span key={c.model}><i className={c.answers===c.planned?'complete':''}/><b>{LANDSCAPE_MODELS.find(m=>m.id===c.model)?.label}</b> {c.answers}/{c.planned} answers</span>)}</div>
  <div className="landscape-chart-heading"><h3>{selected?'Website recommendations':'Website averages across models'}</h3><span>Bar length shows appearance rate · position is shown beside each website</span></div>
  {!result.complete&&<p className="website-coverage-note">Partial coverage: {answers}/{questions.length*models.length} answers available. Averages use saved answers only; missing results are not zeroes.</p>}
  {rows.length ? <><div className="website-ranking-chart" role="group" aria-label="Top websites by appearance rate"><div className="website-ranking-head"><span>Website</span><span>Appearance rate</span><span>Avg. position</span></div><ol>{chartRows.map((r,index)=><li key={r.domain}><button type="button" className="website-ranking-row" aria-pressed={active?.domain===r.domain} onClick={()=>selectSite(r.domain)}><span className="website-ranking-name"><span className="website-ranking-number">{String(index+1).padStart(2,'0')}</span><span><strong>{r.name}</strong><small>{r.domain}</small></span></span><span className="website-ranking-measure"><span className="website-ranking-track"><span style={{width:`${Math.max(2,Math.min(100,r.share/shareMax*100))}%`}}/></span><strong>{r.share.toFixed(1)}%</strong></span><span className="website-ranking-position" aria-label={`Average position ${r.position.toFixed(1)}`}><span className="website-ranking-mobile-position">Position </span>{r.position.toFixed(1)}</span></button></li>)}</ol></div><p className="website-chart-help">Top {chartRows.length} by appearance in saved answers. Select a website to inspect its model results. The table below includes all {rows.length} websites; missing answers are excluded from the average.</p>
  {active&&<aside className="website-detail" aria-label={`Model results for ${active.domain}`}><div><h3>{active.name}</h3><a href={active.url} target="_blank" rel="noreferrer">{active.domain} ↗</a><button aria-label="Close website details" onClick={()=>set({site:''})}>×</button></div><div className="website-model-breakdown">{active.perModel.map(m=><section key={m.model}><h4>{LANDSCAPE_MODELS.find(item=>item.id===m.model)?.label}</h4><strong>{m.share===null?'—':`${m.share.toFixed(1)}%`}</strong><p>{m.appearances}/{m.answers} saved answers</p><small>{m.position===null?'No recommendation position':`Avg. position ${m.position.toFixed(1)}`}</small>{m.queryId&&<Link href={`?query=${encodeURIComponent(m.queryId)}&model=${encodeURIComponent(m.model)}`}>See source answer ↗</Link>}</section>)}</div></aside>}
  <div className="website-table-heading"><h3>All websites <span>{rows.length}</span></h3><UiField label="Find a website" className="website-search-field"><input placeholder="Find a website…" value={search} onChange={e=>{setSearch(e.target.value);setLimit(12)}}/></UiField></div><div className="landscape-table-wrap website-results"><table><caption>{selected?'One model’s saved recommendations':'Each model has equal weight in the average'} · {questions.length} {questions.length===1?'question':'questions'}</caption><thead><tr><th>Website</th><th>Avg. appearance</th><th>Avg. position</th><th>Models recommending</th><th>Questions appearing in</th></tr></thead><tbody>{visible.slice(0,limit).map(r=><tr key={r.domain} aria-selected={active?.domain===r.domain}><th><button onClick={()=>selectSite(r.domain)}>{r.name} ↗</button><small>{r.domain}</small></th><td><span className="website-rate"><i style={{width:`${Math.max(2,r.share)}%`}}/>{r.share.toFixed(1)}%</span></td><td>{r.position.toFixed(1)}</td><td>{r.modelCount}/{result.measuredModels}</td><td>{r.questionCount}/{questions.length}</td></tr>)}</tbody></table>{visible.length>limit&&<button className="website-show-more" onClick={()=>setLimit(limit+12)}>Show more websites ({limit} of {visible.length}) ↓</button>}{!visible.length&&<p>No websites match “{search}”.</p>}</div></> : <p>No saved answer for this selection. This is unmeasured, not a zero score. <button className="website-reset" onClick={()=>set({model:''})}>View available models</button></p>}
  {result.firstDate&&<p className="landscape-note">Observed {result.firstDate}{result.lastDate!==result.firstDate?` — ${result.lastDate}`:''}. Latest published answer per model and question; collection dates can differ.</p>}
  <details className="landscape-details"><summary>How to read this comparison</summary><p>Uses the latest published answer for each question and model. For each model, appearance rate is the share of its saved answers recommending a website. We average those rates with equal weight per model. Average position is the mean of each recommending model’s average position; non-appearances have no position. Missing and failed answers are excluded, never scored as zero. Different coverage can affect averages.</p><p>This measures presence in the selected question set, not universal website quality. Some questions explicitly name websites, so compare within a relevant category or question. These are Folio managed research-agent results, not Google rankings or consumer ChatGPT measurements. Reviewed documentation aliases are grouped; other hostnames remain separate. Source questions, citations and returned reasons remain available below.</p></details>
  <p className="landscape-note"><a href="/leaderboard?view=questions">Explore earlier company-mention cohorts ↗</a></p>
 </section>;
}
