"use client";
import { useSearchParams } from 'next/navigation';
import { PUBLIC_SEARCH_QUERIES, PUBLIC_SEARCH_OBSERVATIONS } from '@/lib/public-search-rankings';
import { websiteLandscape } from '@/lib/website-landscape';
import { LANDSCAPE_MODELS } from '@/lib/model-landscape';
import './model-landscape.css';
export function ModelLandscape() {
 const params=useSearchParams();
 const available=PUBLIC_SEARCH_QUERIES.filter(q=>PUBLIC_SEARCH_OBSERVATIONS.some(o=>o.queryId===q.id));
 const query=PUBLIC_SEARCH_QUERIES.find(q=>q.id===params.get('query'))??available[0];
 const selected=params.get('model')??'';
 const {answers,rows}=websiteLandscape(PUBLIC_SEARCH_OBSERVATIONS,query.id,selected);
 const set=(key:string,value:string)=>{const next=new URLSearchParams(params.toString());if(value)next.set(key,value);else next.delete(key);window.history.pushState(null,'',`${window.location.pathname}?${next}`);};
 const maximum=Math.max(5,...rows.map(r=>Math.ceil(r.position)));
 const x=(share:number)=>72+share*4.7;
 const y=(position:number)=>65+(position-1)/(maximum-1)*280;
 const colors=['#244f3d','#667d54','#987442','#465d68'];
 return <section className="model-landscape website-landscape" aria-labelledby="landscape-title">
  <header className="landscape-heading"><div><p className="landscape-kicker">THE FOLIO INDEX / WEBSITE DISCOVERY</p><h2 id="landscape-title">Which websites<br/><em>get recommended?</em></h2><p className="landscape-intro">See which websites appear in AI answers—and where they appear in the recommendation list.</p></div><div className="landscape-cohort"><strong>{rows.length}</strong><span>websites recommended</span><p>Across {answers} saved {answers===1?'answer':'answers'} to this question</p></div></header>
  <div className="website-controls"><label>Question<select aria-label="Website comparison question" value={query.id} onChange={e=>set('query',e.target.value)}>{!available.some(q=>q.id===query.id)&&<option value={query.id}>{query.query}</option>}{available.map(q=><option key={q.id} value={q.id}>{q.query}</option>)}</select></label><label>Answers from<select aria-label="Website comparison model" value={selected} onChange={e=>set('model',e.target.value)}><option value="">All four models</option>{LANDSCAPE_MODELS.map(m=><option key={m.id} value={m.id}>{m.label}</option>)}</select></label></div>
  <p className="website-question">{query.query}</p>
  <div className="landscape-chart-heading"><h3>Website presence × recommendation position</h3><span>Each dot is a website · Upper right = appears more often and earlier</span></div>
  {rows.length ? <><div className="website-plot"><svg viewBox={`0 0 900 ${Math.max(425,rows.length*30+80)}`} role="img" aria-label="Website appearances and average recommendation position"><rect x="72" y="65" width="470" height="280" fill="#fbf8ee"/>{[0,25,50,75,100].map(v=><g key={v}><line x1={x(v)} x2={x(v)} y1="65" y2="345" stroke="#d5d7c9"/><text x={x(v)} y="370" textAnchor="middle" className="landscape-tick">{v}%</text></g>)}{Array.from({length:maximum},(_,i)=>i+1).map(v=><g key={v}><line x1="72" x2="542" y1={y(v)} y2={y(v)} stroke="#d5d7c9" strokeDasharray="3 5"/><text x="57" y={y(v)+4} textAnchor="end" className="landscape-tick">{v}</text></g>)}<text x="307" y="405" textAnchor="middle" className="landscape-axis">Share of saved answers recommending the website</text><text transform="translate(20 205) rotate(-90)" textAnchor="middle" className="landscape-axis">Average position · 1 is first</text>{rows.map((r,i)=><g key={r.domain}><path d={`M ${x(r.share)} ${y(r.position)} L 590 ${74+i*30}`} fill="none" stroke={colors[i%4]} opacity=".45"/><circle cx={x(r.share)} cy={y(r.position)} r={8+i%3*2} fill={colors[i%4]} fillOpacity=".75" stroke="#f1eddf" strokeWidth="2"><title>{`${r.domain}: ${r.appearances}/${answers} answers, average position ${r.position.toFixed(1)}`}</title></circle><text x="600" y={78+i*30} className="landscape-label">{i+1}. {r.domain}</text></g>)}</svg></div><div className="landscape-table-wrap website-results"><table><caption>Website results · {query.category}</caption><thead><tr><th>Website</th><th>Appears in</th><th>Share of answers</th><th>Average position</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.domain}><th><a href={r.url} target="_blank" rel="noreferrer">{i+1}. {r.name} ↗</a><small>{r.domain}</small></th><td>{r.appearances} / {answers}</td><td>{r.share.toFixed(0)}%</td><td>{r.position.toFixed(1)}</td></tr>)}</tbody></table></div></> : <p>No saved answer for this selection. This is unmeasured, not a zero score.</p>}
  <details className="landscape-details"><summary>How to read this comparison</summary><p>Uses the latest published answer per model for this exact question. Each website hostname counts once per answer; www is normalized, other subdomains remain separate. Average position includes only answers where that website appears. Overlapping dots share the same measurements; the table lists every website.</p><p>These are recommendations returned by Folio’s managed research agents, not Google rankings or measurements of consumer ChatGPT. Missing and failed answers are excluded from the denominator. Small samples and different answer dates limit comparisons. Sources and returned reasons are available below.</p></details>
  <p className="landscape-note"><a href="/leaderboard?view=questions">Explore earlier company-mention cohorts ↗</a></p>
 </section>;
}
