"""Deterministic question authoring; no provider calls or invented observations."""
import json
from pathlib import Path

scenarios = {
'Developer tools': ['a solo developer shipping a first paid product','a two-person startup with a $100 monthly infrastructure budget','a five-person team maintaining an existing TypeScript service','a consultancy delivering separate projects for multiple clients','a product expecting irregular traffic spikes','a team migrating from a self-hosted system','a service handling customer data with strict access requirements','a team supporting customers in both the US and Europe','a prototype that must become maintainable within three months','a team with limited DevOps experience','an established product trying to reduce vendor lock-in'],
'Software & work': ['a two-person remote business','a five-person agency sharing work with external clients','a ten-person team spread across US time zones','a volunteer group with a very limited software budget','a consultant handling several confidential client projects','a team migrating years of content from another tool','a company onboarding new staff every month','a team whose contractors join and leave frequently','a business that needs mobile access while traveling','a team with mixed technical experience','a company evaluating a paid plan before an annual commitment'],
'Shops & brands': ['a first-time online shopper in the United States','a shopper furnishing or outfitting a small urban apartment','a shopper with a strict total purchase budget','someone buying a gift for another adult','a shopper who cannot easily visit a physical store','a shopper comparing an online purchase with local pickup','someone who may need to return an unsuitable purchase','a shopper who prioritizes low maintenance and long service life','someone replacing a frequently used everyday item','a shopper who needs an item before a fixed upcoming date','a shopper comparing several brands before making one purchase'],
'Services & travel': ['a first-time customer with a strict total budget','a solo adult making a booking without prior experience','someone booking well in advance of a fixed date','someone considering a last-minute booking','a customer comparing two providers for the same need','someone whose plans may change after booking','a customer who needs clear accessibility information','someone coordinating a booking with a friend or family member','a customer who needs help understanding exclusions','someone who prefers a slower pace and extra support','a customer checking independent evidence before paying'],
'Learning': ['a complete beginner studying alongside a full-time job','an adult returning to study after several years','a learner with only three hours available each week','a learner with a limited monthly education budget','someone who learns best through practical exercises','a learner seeking structured feedback rather than self-study alone','someone who wants to study primarily on a mobile device','a learner who needs flexible start dates and breaks','someone comparing a short introduction with a longer course','a learner who wants evidence of progress without an expensive certificate','someone who tried self-study before and struggled to stay consistent'],
}
focus = [
('Node.js and PostgreSQL deployment using Vercel, Render, Railway or Cloudflare Workers','runtime compatibility and unsupported Node APIs|database connection pooling and serverless limits|preview deployments and database isolation|scheduled jobs and background task duration|regional placement and latency|logs, rollback and incident recovery|backup and database restoration|recurring charges and traffic-related cost triggers|migration paths and portable configuration'),
('Better Auth, Clerk, WorkOS and Auth0 for a TypeScript SaaS','GitHub and Google sign-in setup|enterprise SSO prerequisites and pricing triggers|organization membership and tenant isolation|account linking and duplicate identities|session revocation and logout behavior|user export and migration options|development and staging environments|MFA and recovery flows|hosting responsibility and operational maintenance'),
('isolated Python sandboxes and occasional GPU batch compute','network egress restrictions|persistent files and reproducible environments|job duration and interruption handling|GPU availability and billing units|secret injection and process isolation|parallel job quotas and rate limits|artifact downloads and retention|cold starts and startup dependencies|cleanup, cancellation and cost visibility'),
('Chroma, Qdrant and Pinecone for document search','metadata filter expressiveness|embedding updates and reindexing|tenant separation and API permissions|hybrid keyword and vector retrieval|backup and data export|hosted versus self-managed operating effort|index size and usage-based costs|regional hosting and data residency|evaluation of retrieval relevance'),
('Firecrawl, Exa and Tavily for source-backed web research','search versus page extraction|citation URLs and provenance fields|JavaScript-heavy page handling|freshness controls and caching|rate limits and concurrency|API failures and partial results|structured extraction schemas|usage units and repeat-request costs|coverage limitations and blocked sites'),
('Sentry and PostHog for web-product observability','error grouping and debugging workflow|funnel and event instrumentation|session replay redaction|sampling and retention controls|source maps and release tracking|access permissions for contractors|usage-based costs and quotas|self-hosted versus hosted options|connecting a production incident to user impact'),
('Notion and Basecamp for shared client projects','client guest visibility|task ownership and due dates|document organization and search|notification volume and follow-up|file export and project archiving|mobile access and offline limitations|contractor offboarding|five-person pricing and guest limits|migration from email and shared documents'),
('team communication tools including Slack','searchable history and retention|external guest permissions|channels versus direct-message organization|video meetings and asynchronous updates|mobile notifications and quiet hours|data exports and deletion controls|per-seat costs and annual commitments|onboarding and offboarding|migration from an existing chat tool'),
('Allbirds and alternative everyday footwear','style-specific sizing evidence|material composition and care|walking comfort claims and limitations|weather suitability|delivery charges and timelines|return conditions and fees|durability evidence and repair options|availability by size and color|total price compared with alternatives'),
('online cotton T-shirts and jeans including Everlane','garment measurements and size charts|fabric composition and stretch|washing and care instructions|fit differences across styles|shipping thresholds and delivery estimates|return windows and exclusions|sale pricing and final-sale restrictions|stock and restock information|construction details and durability evidence'),
('IKEA desks and alternative small-apartment furniture','dimensions and usable workspace|packaged size and transport needs|assembly tools and instructions|delivery versus pickup costs|local inventory reliability|return conditions after assembly|materials and weight limits|replacement parts and maintenance|total cost compared with alternatives'),
('Taskrabbit furniture assembly in New York City','provider experience and selection|hourly rates and minimum hours|platform fees and other charges|scope and excluded work|appointment availability|cancellation and rescheduling|customer preparation requirements|damage support and dispute process|communication before confirming a booking'),
('Intrepid Travel and G Adventures Japan group trips','trip style and pace|solo room sharing and supplements|age eligibility|physical demands and accessibility|included meals and transport|optional activities and extra costs|deposits and cancellation conditions|group size and departures|independent trip reviews and evidence limits'),
('Coursera and edX beginner Python study','prerequisites and first-week difficulty|weekly workload and deadlines|coding exercises and execution environment|feedback and assessment format|free access limitations|certificate cost and payment terms|course updates and instructor information|mobile study limitations|progression to an independent project'),
('Duolingo and complementary beginner Spanish learning','speaking practice and feedback|listening comprehension exercises|grammar explanation depth|free-plan restrictions|paid-plan features and cancellation|lesson pacing and review|offline and mobile use|progress measures and their limitations|when a teacher or conversation partner helps'),
('Browserbase for Playwright browser automation','persistent login contexts|session duration and timeouts|browser regions and latency|recordings and retention|proxy and network options|parallel session limits|download and upload handling|debugging failed navigation|per-session usage and cost attribution'),
('Resend transactional email','domain verification and DNS|SPF, DKIM and DMARC setup|webhook verification and delivery events|bounce and suppression handling|API keys and environment separation|sending limits and rate control|templates and localization|message retention and data controls|pricing and migration from another sender'),
('Stripe for a US software business','account eligibility and verification|one-time checkout setup|subscription lifecycle handling|webhook signatures and replay protection|test mode and production cutover|refunds and dispute handling|payment methods and currency support|tax tooling and its limitations|fees, payouts and reconciliation'),
('Temporal for Node.js workflows','workflow versus activity boundaries|retry policy and idempotency|timeouts and long-running work|workflow versioning|worker deployment and scaling|external API failures|visibility and debugging|cloud versus self-hosted operations|cost and migration from a job queue'),
('Notion for agency client projects','guest access and page sharing|database views and task tracking|permission inheritance|client-facing document organization|project templates and setup effort|notifications and reminders|archiving and export|paid seats and guest caps|offboarding clients and contractors'),
('Slack history and guest access','free-plan searchable history|message deletion and retention|single-channel guest rules|multi-channel guests and seat billing|Slack Connect versus guest accounts|exports and administrative controls|search across files and channels|migration from a free plan|annual billing and inactive users'),
('Basecamp for agency client projects','client visibility boundaries|to-dos and responsibility|documents and file organization|message boards versus chat|project templates and scheduling|notification preferences|archive and export behavior|pricing for staff and clients|mobile access and handoff'),
('Notion as an internal knowledge handbook','search and information structure|page permissions and teamspaces|offline access limitations|export formats and data portability|database relationships in exports|version history and recovery|onboarding and content ownership|integrations and API access|migration effort and lock-in'),
('IKEA product ordering and delivery in the US','desk measurements and room fit|packaging and transport dimensions|stock by store and delivery area|delivery service levels and fees|pickup instructions and timing|assembly requirements|missing parts and support|order changes and cancellation|total cost including services'),
('Allbirds product fit and care in the US','size recommendations by style|width and fit information|wool versus tree-fiber materials|washing instructions|wet-weather limitations|outsole and everyday use|returns after trying on|shipping and stock|material claims and supporting evidence'),
('Everlane T-shirts and jeans in the US','body versus garment measurements|fit notes across styles|cotton blend and stretch content|care and shrinkage guidance|rise and inseam options|stock across sizes|returns and final sale|delivery and total cost|construction and material claims'),
('IKEA US returns and purchase services','unopened return conditions|assembled furniture return conditions|proof of purchase requirements|collection service and fees|assembly service scope|delivery damage reporting|refund method and timing|exclusions and altered items|comparison of purchase channels'),
('Taskrabbit local furniture assembly bookings in New York City','postcode service availability|provider profile evidence|task scope and estimates|scheduling and arrival windows|minimum booking durations|tools and customer preparation|stairs, parking and location details|rescheduling process|completion and dispute support'),
('Intrepid Travel Japan itineraries','trip style categories|daily pace and free time|group size|age rules|room sharing and supplements|fitness and accessibility information|meals and transport inclusions|optional costs|booking flexibility and cancellations'),
('G Adventures Japan itineraries','travel style categories|age eligibility|group size|room sharing and single supplements|daily pace and transport|physical rating and support|included activities and meals|extra charges and budgeting|deposits and cancellation terms'),
('Taskrabbit pricing and cancellation','hourly rates|minimum time charges|platform service fees|expenses and reimbursements|estimates versus final billing|cancellation windows|rescheduling fees|invoice breakdown and tips|disputes and refund requests'),
('Coursera beginner Python courses','entry prerequisites|weekly workload|course sequence and progression|practical coding exercises|assessment feedback|instructor and update information|flexible deadlines|mobile access|course completion versus job readiness'),
('Duolingo beginner Spanish practice','lesson formats|speaking exercises|listening practice|grammar explanations|review and spaced practice|free versus paid experience|subscription cancellation|progress measures|complementary teacher-led practice'),
('edX beginner Python courses','prerequisites|weekly study hours|course start and end dates|coding environment|graded and ungraded exercises|audit access limits|instructor support|certificate requirements|progression to further study'),
('Coursera course access and payment','audit or preview availability|access to graded assignments|certificate fees|subscription versus single-course payment|trial conversion rules|cancellation timing|refund eligibility|financial aid availability|access after ending payment'),
]

def expand(artifact):
    original = artifact['queries']
    if len(original) != 35 or len(set(q['category'] for q in original)) != 35:
        raise ValueError('Expected the reviewed 35-category seed; refusing to expand an altered taxonomy')
    new=[]
    for base,(subject,topics) in zip(original,focus,strict=True):
        topics=topics.split('|')
        assert len(topics)==9
        for i,scenario in enumerate(scenarios[base['audience']]):
            for j,topic in enumerate(topics):
                new.append({**base,'id':f"{base['id']}-s{i+1:02d}-q{j+1:02d}", 'query':f"For {scenario}, how should I evaluate {subject}, specifically {topic}? Use current official sources, distinguish available options from restrictions, and explain the evidence I should check before choosing. If a feature or term is unavailable or unclear, say so rather than assuming it exists."})
    assert len(new)==3465 and len(set(q['query'] for q in new))==3465
    return {**artifact,'queries':original+new}

if __name__=='__main__':
    path=Path('src/data/public-search-rankings.json')
    value=expand(json.loads(path.read_text()))
    path.write_text(json.dumps(value,indent=2,ensure_ascii=False)+'\n')
    print('35 categories; 100 questions each; 3500 total; 3465 newly authored; observations preserved')
